window.SCHOOLS = [
  {
    id: "aalto",
    name: "Aalto University",
    cn: "阿尔托大学",
    city: "赫尔辛基",
    country: "芬兰",
    position: "研究型设计、北欧公共性与跨学科建筑教育的综合入口。",
    programs: [
      {
        id: "aalto-architecture",
        name: "Architecture",
        degree: "MSc Architecture",
        duration: "2 年 · 120 ECTS",
        language: "英语",
        tuition: "€17,000 / 年",
        deadline: "2026.12.07—2027.01.05",
        status: "2027 已公布",
        tags: ["建筑设计", "公共性", "设计研究"],
        intro: "将建筑设计与城市、建造、景观、社会议题及跨学科研究并置，不以单一形式风格定义学生。",
        suitable: "建筑本科扎实，能把研究问题转译为空间、材料和建造判断的申请者。",
        portfolio: "用 3–5 个完整项目呈现问题、迭代、图纸、模型与技术判断；团队项目明确个人贡献。",
        requirements: "相关建筑本科；按 Architecture major 当年指令提交作品集及申请材料。",
        warning: "不要把 Urban Studies and Planning 的学费、作品集要求或城市研究方向与本项目混用。",
        url: "https://www.aalto.fi/en/study-options/architecture-master-of-science-in-architecture"
      },
      {
        id: "aalto-urban",
        name: "Urban Studies and Planning",
        degree: "MSc Architecture · Architecture specialisation",
        duration: "2 年 · 120 ECTS",
        language: "英语",
        tuition: "以当轮项目页为准",
        deadline: "2027 轮待项目页确认",
        status: "待复核",
        tags: ["城市研究", "跨学科", "公共政策"],
        intro: "偏向城市研究、规划与跨学科分析，是建筑学位下的城市方向，不是常规建筑设计硕士的替代品。",
        suitable: "明确希望转向城市研究、治理、住房或公共政策，并保留空间思维的申请者。",
        portfolio: "突出田野、数据、城市尺度分析与空间策略的连续性。",
        requirements: "相关背景；具体资格与作品集格式按 2027 申请页面核查。",
        warning: "如果目标是传统建筑师训练，应优先评估 Architecture major。",
        url: "https://www.aalto.fi/en/study-options/masters-programme-in-urban-studies-and-planning-msc-in-architecture"
      }
    ]
  },
  {
    id: "tampere",
    name: "Tampere University",
    cn: "坦佩雷大学",
    city: "坦佩雷",
    country: "芬兰",
    position: "把可持续转型落实到建筑空间、材料与既有环境的现实型项目。",
    programs: [{
      id: "tampere-sustainable",
      name: "Sustainable Architecture",
      degree: "MSc Architecture",
      duration: "2 年 · 120 ECTS",
      language: "英语",
      tuition: "€12,000 / 年",
      deadline: "2027 日期待 Studyinfo 公布",
      status: "待更新",
      tags: ["可持续", "再利用", "气候适应"],
      intro: "以环境、文化与社会挑战为核心，重视既有环境、低碳转型与现实建成问题，而非只做节能技术。",
      suitable: "有再利用、住房、公共建筑、材料生命周期或气候适应项目的建筑本科生。",
      portfolio: "证明环境策略怎样改变空间、结构、材料、生命周期和使用方式，避免仅使用绿色标签。",
      requirements: "相关建筑学位、英语证明及 Studyinfo 当轮要求的补充材料。",
      warning: "旧有 12 月至 1 月的日期不能当作 2027 已公布截止。",
      url: "https://www.tuni.fi/en/tau/masters-programmes/sustainable-architecture-architecture"
    }]
  },
  {
    id: "oulu",
    name: "University of Oulu",
    cn: "奥卢大学",
    city: "奥卢",
    country: "芬兰",
    position: "从北方环境、地域材料与技术—空间关系切入的专业建筑教育。",
    programs: [{
      id: "oulu-architecture",
      name: "Architecture",
      degree: "Master's in Architecture",
      duration: "2 年",
      language: "英语",
      tuition: "€14,000 / 年",
      deadline: "2027.01.07—01.21",
      status: "2027 已公布",
      tags: ["寒地建筑", "木构", "可持续"],
      intro: "正式项目名为 Architecture；北方环境、可持续建筑和地域性构成鲜明语境。",
      suitable: "愿意研究寒地生活、气候、木构、社区与技术实现的建筑本科生。",
      portfolio: "用剖面、围护、采光、季节环境与材料逻辑证明设计能力。",
      requirements: "相关建筑本科与英语证明；最终以 Studyinfo 当轮页面为准。",
      warning: "第二年 40% tuition waiver 不是标准学费，不能把减免后的 €9,800 作为报价。",
      url: "https://www.oulu.fi/en/apply/masters-architecture"
    }]
  },
  {
    id: "kth",
    name: "KTH Royal Institute of Technology",
    cn: "瑞典皇家理工学院",
    city: "斯德哥尔摩",
    country: "瑞典",
    position: "技术大学语境中的建筑设计，连接城市、社会与可验证的技术系统。",
    programs: [{
      id: "kth-architecture",
      name: "Architecture",
      degree: "MSc Architecture",
      duration: "2 年 · 120 ECTS",
      language: "英语",
      tuition: "SEK 600,000 / 全项目",
      deadline: "2027.01.15 · 材料 02.01",
      status: "2027 已公布",
      tags: ["建筑设计", "技术整合", "城市"],
      intro: "三学期课程与 studio，末学期完成学位项目，强调建筑设计与建成环境研究的连接。",
      suitable: "能同时处理空间组织、城市尺度和技术实现的建筑本科生。",
      portfolio: "以完整项目说明设计命题与技术、环境系统之间的关系，避免堆叠竞赛效果图。",
      requirements: "相应建筑本科及 Swedish national admissions 的通用与项目条件。",
      warning: "学费以瑞典克朗公布，不用未标日期的欧元换算值作固定报价。",
      url: "https://www.kth.se/en/studies/master/architecture/msc-architecture-1.48041"
    }]
  },
  {
    id: "chalmers",
    name: "Chalmers University of Technology",
    cn: "查尔姆斯理工大学",
    city: "哥德堡",
    country: "瑞典",
    position: "在专业建筑设计与社会—生态转型之间提供两条清晰路径。",
    programs: [
      {
        id: "chalmers-aud",
        name: "Architecture and Urban Design",
        degree: "MSc",
        duration: "2 年 · 120 ECTS",
        language: "英语",
        tuition: "按 2027 fee page 确认",
        deadline: "通常 1 月中旬",
        status: "待更新",
        tags: ["建筑设计", "城市设计", "专业实践"],
        intro: "设计主导，聚焦空间形态、城市公共性、建筑—城市关系，并兼具理论与研究方法。",
        suitable: "希望深化专业建筑与城市设计、具有完整空间表达能力的申请者。",
        portfolio: "突出不同尺度之间的连续性，以及空间、构造和城市判断的整合。",
        requirements: "180 ECTS 等值本科及项目特定先修、英语和作品集要求。",
        warning: "不要以泛称 Architecture MSc 代替具体项目名。",
        url: "https://www.chalmers.se/en/education/find-masters-programme/architecture-and-urban-design-msc/"
      },
      {
        id: "chalmers-apbs",
        name: "Architecture and Planning Beyond Sustainability",
        degree: "MSc",
        duration: "2 年 · 120 ECTS",
        language: "英语",
        tuition: "按 2027 fee page 确认",
        deadline: "通常 1 月中旬",
        status: "待更新",
        tags: ["可持续", "社会生态", "规划"],
        intro: "从建造、郊区、社会包容、地方语境与治理出发，讨论超越口号式可持续性的转型。",
        suitable: "能形成研究问题，处理资源、利益相关者、治理与空间后果的申请者。",
        portfolio: "以真实情境、证据与设计后果建立论证，不做抽象的绿色未来。",
        requirements: "相关建筑、工程、技术或科学本科，并满足项目特定条件。",
        warning: "与 A&UD 的动机和作品集重点必须区分。",
        url: "https://www.chalmers.se/en/education/find-masters-programme/architecture-and-planning-beyond-sustainability-msc/"
      }
    ]
  },
  {
    id: "lund",
    name: "Lund University",
    cn: "隆德大学",
    city: "隆德",
    country: "瑞典",
    position: "从全面建筑训练到数字研究、可持续城市设计的多入口体系。",
    programs: [
      {
        id: "lund-architecture",
        name: "Architecture",
        degree: "MSc",
        duration: "2 年 · 120 ECTS",
        language: "英语 · English 6",
        tuition: "以 SEK 当年项目页为准",
        deadline: "通常 2027.01.15",
        status: "待更新",
        tags: ["建筑设计", "建造", "综合训练"],
        intro: "常规建筑硕士，强调建筑基本功、空间逻辑、建造与完整的设计过程。",
        suitable: "希望继续全面专业建筑训练的建筑本科生。",
        portfolio: "单一数字 PDF；平立剖、构造与过程必须完整，以当轮 10MB 等格式指令为准。",
        requirements: "建筑学本科或等同背景、个人数字作品集、statement 与 English 6。",
        warning: "以 SEK 收费，旧欧元换算不能直接作为报价。",
        url: "https://www.lunduniversity.lu.se/study/architecture-masters-programme-TAMAR"
      },
      {
        id: "lund-daef",
        name: "Digital Architecture and Emergent Futures",
        degree: "MSc",
        duration: "2 年 · 120 ECTS",
        language: "英语 · English 6",
        tuition: "以 SEK 当年项目页为准",
        deadline: "通常 2027.01.15",
        status: "待更新",
        tags: ["计算设计", "数字制造", "材料研究"],
        intro: "建筑实践与研究的交叉，连接计算、bioDigital Matter、数字建造与未来建成环境。",
        suitable: "已有计算设计、材料实验、制造或批判技术叙事的建筑申请者。",
        portfolio: "说明数字工具背后的材料、构造与环境问题，参数化形式不能替代建筑结果。",
        requirements: "相关建筑背景、作品集、statement 与 English 6。",
        warning: "这是明确的数字研究方向，不应混同为通用 M.Arch。",
        url: "https://www.lunduniversity.lu.se/study/digital-architecture-and-emergent-futures-masters-programme-TAAEF"
      },
      {
        id: "lund-sud",
        name: "Sustainable Urban Design",
        degree: "MSc",
        duration: "2 年",
        language: "英语 · English 6",
        tuition: "以当年项目页为准",
        deadline: "通常 2027.01.15",
        status: "待更新",
        tags: ["城市设计", "可持续", "跨学科"],
        intro: "从城市尺度处理可持续转型，接受建筑、景观、物理规划与城市设计相关背景。",
        suitable: "作品集中有城市、景观、规划或社会空间连续研究的申请者。",
        portfolio: "突出尺度转换、田野证据、空间规则与城市策略。",
        requirements: "相关本科、个人数字作品集与 English 6。",
        warning: "跨学科友好不等于没有空间设计门槛。",
        url: "https://www.lunduniversity.lu.se/study/sustainable-urban-design-masters-programme-TASUD"
      }
    ]
  },
  {
    id: "umea",
    name: "Umeå School of Architecture",
    cn: "于默奥建筑学院",
    city: "于默奥",
    country: "瑞典",
    position: "艺术与科学之间的实验性工作室，强调社会议题、制作与批判性城市观察。",
    programs: [{
      id: "umea-aud",
      name: "Architecture and Urban Design",
      degree: "Artistic Master's Degree",
      duration: "2 年 · 120 ECTS",
      language: "英语",
      tuition: "SEK 473,600 / 全项目",
      deadline: "通常 1 月中旬",
      status: "待更新",
      tags: ["实验建筑", "社会空间", "设计制作"],
      intro: "把 studio 当作实验室，讨论气候变化、不平等、迁移与城市设计，并处于跨艺术校园环境。",
      suitable: "能以空间、社会、艺术与制作形成独立论述的建筑本科生。",
      portfolio: "保留清晰的建筑设计能力，同时呈现批判观察、手作、过程和个人方法。",
      requirements: "建筑本科或等同背景；学术材料走统一平台，portfolio 按学校方式单独提交。",
      warning: "授予艺术硕士，须与瑞典五年制专业 Architecture Programme 区分。",
      url: "https://www.umu.se/en/umea-school-of-architecture/education/programmes/masters-programme-in-architecture-and-urban-design/"
    }]
  },
  {
    id: "aarhus",
    name: "Aarhus School of Architecture",
    cn: "奥胡斯建筑学院",
    city: "奥胡斯",
    country: "丹麦",
    position: "将艺术性、研究、专业实践与社会参与放在同一工作室体系中。",
    programs: [{
      id: "aarhus-architecture",
      name: "Architecture",
      degree: "Master in Architecture",
      duration: "2 年",
      language: "英语路径 · 当轮确认",
      tuition: "€18,000 / 年（2026 非欧盟）",
      deadline: "2027 call 待发布",
      status: "待更新",
      tags: ["建筑设计", "社会参与", "设计研究"],
      intro: "studio、研究与实践并重，以面对变化世界的建筑解法为总体方向。",
      suitable: "有建筑本科、愿意把实验与现实议题共同推进且资金规划充分的申请者。",
      portfolio: "把场地阅读、策略、建筑空间与技术表达压缩为清晰主线。",
      requirements: "依年度 application guidelines 与 portfolio requirements 核查。",
      warning: "RIBA Part 2 适用性须按入学年度重新核实；学校不提供校内 financial aid。",
      url: "https://aarch.dk/en/full-degree-student-admission/"
    }]
  },
  {
    id: "kadk",
    name: "Royal Danish Academy",
    cn: "丹麦皇家建筑、设计与艺术学院",
    city: "哥本哈根",
    country: "丹麦",
    position: "以具体 studio 为核心，在建筑、城市、极端环境、材料与转型之间选择方向。",
    programs: [
      {
        id: "kadk-critical-sustainability",
        name: "Political Architecture: Critical Sustainability",
        degree: "MA Architecture",
        duration: "2 年",
        language: "英语",
        tuition: "2027 call 待确认",
        deadline: "2027 call 待发布",
        status: "待更新",
        tags: ["批判性可持续", "政治建筑", "社会生态"],
        intro: "从政治、资源与社会关系审视可持续性，适合把设计作为批判和现实介入方式的申请者。",
        suitable: "具备建筑本科、研究能力与社会—生态议题项目的申请者。",
        portfolio: "让研究问题落到现状阅读、空间决策、材料和构造，不只呈现立场。",
        requirements: "国家认可学校的 Bachelor in Architecture 或 architectural studies，及当轮完整材料。",
        warning: "studio 名称、开放状态、名额与费用必须按 2027 admissions portal 复核。",
        url: "https://kglakademi.dk/en/admission-master"
      },
      {
        id: "kadk-extreme",
        name: "Architecture and Extreme Environments",
        degree: "MA Architecture",
        duration: "2 年",
        language: "英语",
        tuition: "2027 call 待确认",
        deadline: "2027 call 待发布",
        status: "待更新",
        tags: ["极端环境", "气候", "原型"],
        intro: "以极端气候与地域条件为设计问题场，结合环境研究、原型与建筑空间。",
        suitable: "有气候、地域、材料实验或实地研究经验的建筑申请者。",
        portfolio: "呈现环境证据如何驱动剖面、围护、构造与使用方式。",
        requirements: "建筑或 architectural studies 本科；按年度 studio 开放情况申请。",
        warning: "不要只把极端环境当作视觉题材。",
        url: "https://kglakademi.dk/en/admission-master"
      },
      {
        id: "kadk-urbanism",
        name: "Urbanism & Societal Change",
        degree: "MA Architecture",
        duration: "2 年",
        language: "英语",
        tuition: "2027 call 待确认",
        deadline: "2027 call 待发布",
        status: "待更新",
        tags: ["城市", "社会转型", "公共性"],
        intro: "以城市化与社会变化为核心，连接空间策略、公共性与跨尺度研究。",
        suitable: "有城市、住房、迁移、治理或公共空间项目的建筑申请者。",
        portfolio: "强化城市研究、图纸尺度和空间原型之间的连续性。",
        requirements: "建筑或 architectural studies 本科；具体要求按当年 studio。",
        warning: "跨尺度研究不能替代建筑和空间表达。",
        url: "https://kglakademi.dk/en/admission-master"
      }
    ]
  },
  {
    id: "aho",
    name: "Oslo School of Architecture and Design",
    cn: "奥斯陆建筑与设计学院",
    city: "奥斯陆",
    country: "挪威",
    position: "长学制、强 studio 与自主 diploma 的专业建筑师培养后段。",
    programs: [{
      id: "aho-architecture",
      name: "Architecture",
      degree: "Master of Architecture",
      duration: "2.5 年 · 150 ECTS",
      language: "英语路径 · 当轮确认",
      tuition: "非欧盟费用按当轮确认",
      deadline: "通常 12.05—02.02",
      status: "待更新",
      tags: ["建筑设计", "自主研究", "跨学科"],
      intro: "连接艺术、人文、社会科学与工程方法，并以自主 diploma 完成专业训练。",
      suitable: "已有扎实建筑本科训练、能够建立研究立场并持续迭代的成熟申请者。",
      portfolio: "证明连续的建筑教育基础与独立推进问题的能力；单一 PDF 格式按当轮要求。",
      requirements: "建筑本科或等值 180 ECTS、英语与 portfolio。",
      warning: "项目为 2.5 年而不是常见两年制；名额与学费不能固定承诺。",
      url: "https://www.aho.no/english/studies/programmes/master-of-architecture/admission/"
    }]
  },
  {
    id: "bas",
    name: "Bergen School of Architecture",
    cn: "卑尔根建筑学院",
    city: "卑尔根",
    country: "挪威",
    position: "小型、批判性、实践与艺术并置的建筑共同体。",
    programs: [{
      id: "bas-architecture",
      name: "Architecture · Year 4 entry",
      degree: "Master in Architecture",
      duration: "后两年 · 每学期 30 ECTS",
      language: "英语",
      tuition: "NOK 325,292 / 年（2026 非欧盟）",
      deadline: "最近公开 04.15",
      status: "待更新",
      tags: ["实验建筑", "设计建造", "批判实践"],
      intro: "进入五年制建筑教育的第 4、5 年，以 semester package 整合建筑、理论、艺术与建造。",
      suitable: "已有建筑本科、作者性强，希望在自由 studio 深化明确议题的申请者。",
      portfolio: "明确个人角色、过程、模型、材料、图纸与最终论证。",
      requirements: "至少完成建筑本科；成绩单、作品集及当轮申请材料。",
      warning: "不是面向所有本科背景的普通两年制转换硕士；非欧盟费用较高且无奖学金。",
      url: "https://bas.org/en/opptak/"
    }]
  },
  {
    id: "mendrisio",
    name: "USI Accademia di Architettura",
    cn: "门德里西奥建筑学院",
    city: "门德里西奥",
    country: "瑞士",
    position: "高密度建筑文化、历史与当代设计教育，建立在意大利语语境中。",
    programs: [{
      id: "mendrisio-architecture",
      name: "Architecture",
      degree: "Master in Architecture",
      duration: "2 年 · 120 ECTS + 9 个月实习",
      language: "主语言意大利语 · 部分英语",
      tuition: "CHF 4,000 / 学期（国际生）",
      deadline: "签证申请人通常 02.15",
      status: "非全英文",
      tags: ["建筑文化", "历史理论", "设计批评"],
      intro: "优势在建筑史、理论、领土与 studio 密度，但主教学语言是意大利语。",
      suitable: "已有或愿长期投入意大利语，并对建筑文化、城市与设计批评有明确兴趣的申请者。",
      portfolio: "强调历史与设计的互相转译、强有力的平立剖以及实体和构造推理。",
      requirements: "建筑本科；成绩、课程表、CV、动机、作品集及推荐信等。",
      warning: "不能列入“只需英语即可完成”的项目名单。",
      url: "https://www.arc.usi.ch/en/study-architecture/master/architecture"
    }]
  },
  {
    id: "florence",
    name: "University of Florence",
    cn: "佛罗伦萨大学",
    city: "佛罗伦萨",
    country: "意大利",
    position: "在历史城市与遗产语境中推进当代建筑设计。",
    programs: [{
      id: "florence-architectural-design",
      name: "Architecture · Architectural Design",
      degree: "LM-4 second-cycle degree",
      duration: "通常 2 年",
      language: "英语 B2 路径",
      tuition: "按身份与年度费用表",
      deadline: "2027 international call 待发布",
      status: "待更新",
      tags: ["建筑设计", "历史城市", "遗产"],
      intro: "英文 Architectural Design curriculum，适合在历史环境与当代介入之间形成具体设计论证。",
      suitable: "建筑本科扎实，并有改造、修复、历史环境或理论—设计项目的申请者。",
      portfolio: "展示历史条件如何进入空间、图纸与材料判断，避免仅把城市当作图像风格。",
      requirements: "建筑或相当背景、英文 B2；名额、作品集和面试按年度 call。",
      warning: "不要与校内一年制 professional Master course 混淆；旧学费只是估算。",
      url: "https://www.unifi.it/en/study-us/degree-programmes/international-courses/international-degree-programmes"
    }]
  },
  {
    id: "iuav",
    name: "Università Iuav di Venezia",
    cn: "威尼斯建筑大学",
    city: "威尼斯",
    country: "意大利",
    position: "以威尼斯的建筑、城市、景观与遗产作为当代实验语境。",
    programs: [{
      id: "iuav-architecture",
      name: "Architecture",
      degree: "MA Architecture",
      duration: "2 年",
      language: "英语",
      tuition: "最高约 €2,806 / 年（2026/27）",
      deadline: "2027 轮待发布",
      status: "待更新",
      tags: ["建筑设计", "城市", "遗产改造"],
      intro: "全英文建筑硕士，将城市与历史环境研究和当代空间设计结合。",
      suitable: "有城市剖析、改造、修复或历史环境设计能力的建筑本科生。",
      portfolio: "用图纸和材料判断说明历史条件怎样转化为设计策略。",
      requirements: "建筑本科或经评估的等同背景；按年度 call 提交学历、课程、语言和作品集。",
      warning: "学费是最高额参考，语言考试与截止均以 2027 call 为准。",
      url: "https://www.iuav.it/en/didattica/lauree-magistrali/architecture"
    }]
  },
  {
    id: "polito",
    name: "Politecnico di Torino",
    cn: "都灵理工大学",
    city: "都灵",
    country: "意大利",
    position: "以建造、城市、遗产或可持续形成明确的专业方向选择。",
    programs: [
      {
        id: "polito-construction-city",
        name: "Architecture Construction City",
        degree: "MSc Architecture",
        duration: "2 年",
        language: "按 curriculum · 英语路径需 B2",
        tuition: "按年度 fee guide",
        deadline: "按年度申请轮次",
        status: "待更新",
        tags: ["建造", "城市", "建筑设计"],
        intro: "强调建筑、建造和城市之间的综合能力。",
        suitable: "图纸、构造、城市分析都较完整，且能证明课程匹配度的建筑本科生。",
        portfolio: "呈现从城市条件到建筑与构造的连续推演。",
        requirements: "学位、成绩、课程 syllabus、CV、语言、作品集与学历认证材料。",
        warning: "先确认具体 curriculum 的授课语言；不能把双语要求套给全部项目。",
        url: "https://www.polito.it/en/education/applying-studying-graduating/admissions-and-enrolment/master-s-degree-programmes/applicants-with-a-non-italian-qualification"
      },
      {
        id: "polito-sustainability",
        name: "Architecture for Sustainability",
        degree: "MSc Architecture",
        duration: "2 年",
        language: "英语路径需 B2",
        tuition: "按年度 fee guide",
        deadline: "按年度申请轮次",
        status: "待更新",
        tags: ["可持续", "更新", "环境性能"],
        intro: "把环境、更新、性能与建筑设计结合，方向明确且重视技术和课程先修。",
        suitable: "有环境策略、既有建筑更新或性能—空间整合项目的申请者。",
        portfolio: "让性能证据、材料与空间结果形成因果链。",
        requirements: "相关本科和课程匹配；英语 B2 及项目当轮材料。",
        warning: "全英文项目不额外要求意大利语 B2。",
        url: "https://www.polito.it/en/education/applying-studying-graduating/admissions-and-enrolment/master-s-degree-programmes/applicants-with-a-non-italian-qualification"
      },
      {
        id: "polito-heritage",
        name: "Architecture for Heritage",
        degree: "MSc Architecture",
        duration: "2 年",
        language: "按 curriculum 核查",
        tuition: "按年度 fee guide",
        deadline: "按年度申请轮次",
        status: "待更新",
        tags: ["遗产", "修复", "建筑历史"],
        intro: "聚焦历史建成环境、修复与转化，要求设计和知识结构同时连续。",
        suitable: "有建筑史、测绘、修复、再利用或遗产介入项目的申请者。",
        portfolio: "用现状、病理或历史研究支持具体空间和构造决策。",
        requirements: "相关建筑背景、课程先修及具体语言配置。",
        warning: "必须读取对应 academic regulations，不能只按学校总名申请。",
        url: "https://www.polito.it/en/education/applying-studying-graduating/admissions-and-enrolment/master-s-degree-programmes/applicants-with-a-non-italian-qualification"
      }
    ]
  },
  {
    id: "iceland",
    name: "Iceland University of the Arts",
    cn: "冰岛艺术大学",
    city: "雷克雅未克",
    country: "冰岛",
    position: "以北大西洋环境、文化、材料与艺术实验展开的小规模建筑教育。",
    programs: [{
      id: "iceland-march",
      name: "Architecture",
      degree: "M.Arch",
      duration: "2 年 · 120 ECTS",
      language: "英语",
      tuition: "2027 非 EEA 学费待公布",
      deadline: "2026 轮为 03.02",
      status: "待更新",
      tags: ["地域", "材料实验", "艺术实践"],
      intro: "把极端气候、岛屿环境、文化与空间实践连接，处于小规模艺术院校语境。",
      suitable: "有原创空间方法、材料实验和环境观察的建筑申请者。",
      portfolio: "呈现独立探索和可落地的建筑尺度证据，不把冰岛仅当作视觉题材。",
      requirements: "建筑本科或足够建筑训练、作品集和项目申请文件；英语要求按当轮。",
      warning: "自 2026 秋起非 EEA 等申请者开始收学费，旧 ISK 100,000 不是可靠年学费。",
      url: "https://www.lhi.is/en/namsleid/architects-include/"
    }]
  },
  {
    id: "archip",
    name: "ARCHIP",
    cn: "布拉格建筑学院",
    city: "布拉格",
    country: "捷克",
    position: "小规模国际 studio 与高频导师反馈并重的英语建筑专业路径。",
    programs: [{
      id: "archip-master",
      name: "Architecture and Urbanism",
      degree: "Master",
      duration: "2 年 · 4 学期",
      language: "英语 · B2",
      tuition: "€4,300 / 学期（当前 handbook）",
      deadline: "EU 2026 轮为 07.31",
      status: "待更新",
      tags: ["建筑实践", "城市", "小班工作室"],
      intro: "整合设计、历史、理论、研究与专业实践，研究生规模小、导师讨论密度高。",
      suitable: "需要高频反馈、希望强化专业设计与表达的建筑本科生。",
      portfolio: "概念必须转化为建筑方案、技术与场地关系。",
      requirements: "建筑本科、学历成绩、portfolio、动机及在线系统材料。",
      warning: "非 EU 与签证申请者应提前确认；旧 2 月截止不再可靠。",
      url: "https://www.archip.eu/master-programme/"
    }]
  },
  {
    id: "liechtenstein",
    name: "University of Liechtenstein",
    cn: "列支敦士登大学",
    city: "瓦杜兹",
    country: "列支敦士登",
    position: "小班导师制下连接阿尔卑斯地域、建造、材料与研究实践。",
    programs: [{
      id: "liechtenstein-architecture",
      name: "Architecture",
      degree: "MSc Architecture",
      duration: "2 年 · 120 ECTS",
      language: "英语",
      tuition: "CHF 1,250 / 学期（其他国籍）",
      deadline: "非 EU 需按签证周期确认",
      status: "待更新",
      tags: ["小班", "建造", "地域"],
      intro: "约 30–35 人的小班环境，实践与研究并行，可围绕材料、住房、地域与跨学科合作深化。",
      suitable: "希望紧密导师沟通，并有材料、结构、环境或地域设计作品的建筑本科生。",
      portfolio: "突出专注的建筑问题、图纸、模型与材料工作，并说明与可选 major 的关联。",
      requirements: "相关建筑学士（通常 180 ECTS）、portfolio、学历与成绩材料。",
      warning: "非 EU 截止通常早于 EU；语言证书与具体 major 每年核查。",
      url: "https://www.uni.li/en/studies/study-programmes/msc-architecture"
    }]
  }
];
