// Application data audited against official programme/admissions pages on 2026-08-17.
window.SCHOOLS = [
  {
    id: "aalto",
    name: "Aalto University",
    cn: "阿尔托大学",
    city: "赫尔辛基",
    country: "芬兰",
    position: "在技术、科学与艺术之间培养建筑设计能力，并强调社会责任、可持续性、实验和跨学科协作。",
    programs: [
      {
        id: "aalto-architecture",
        name: "Architecture",
        degree: "MSc Architecture",
        duration: "2 年 · 120 ECTS",
        language: "英语",
        tuition: "€20,000 / 年（最新：2026 入学）",
        deadline: "最新：2025.12.01—2026.01.02 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["建筑设计", "建造", "设计研究"],
        intro: "以建筑设计为核心，深化技术、科学与艺术思维；可在木构、建筑设计与再利用、人本与福祉、计算设计、保护及城市设计与规划等领域发展。",
        suitable: "建筑本科扎实，能把研究问题转译为空间、材料和建造判断的申请者。",
        portfolio: "2026 要求：最多 24 页、最大 A3 的 PDF；至少 3 个个人完成的在校项目，团队项目须标明个人贡献；作品集内整合 1 页 CV、最多 400 词动机信和最多 600 词自我反思信。",
        requirements: "建筑学本科或等值训练；须提交项目指定材料，并对申请中使用 AI 的位置与用途作简短声明；官网明确不考虑推荐信。2027 格式发布后再复核。",
        interview: "必需（入围后）：通过第一阶段的申请者进入第二阶段线上面试。",
        warning: "不要把 Urban Studies and Planning 的学费、作品集要求或城市研究方向与本项目混用。",
        url: "https://www.aalto.fi/en/study-options/architecture-master-of-science-in-architecture"
      },
      {
        id: "aalto-urban",
        name: "Urban Studies and Planning",
        degree: "MSc Architecture · Architecture specialisation",
        duration: "2 年 · 120 ECTS",
        language: "英语",
        tuition: "€17,000 / 年（最新：2026 入学）",
        deadline: "最新：2025.12.01—2026.01.02 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["城市研究", "跨学科", "公共政策"],
        intro: "以跨学科方式处理复杂城市发展挑战，在理论、历史与概念知识之外训练城市研究、规划和实践方法；Architecture specialisation 保留建筑学位资格要求。",
        suitable: "明确希望转向城市研究、治理、住房或公共政策，并保留空间思维的申请者。",
        portfolio: "2026 要求：最多 20 页 PDF，整合 CV 与最多 400 词动机信；突出建筑设计基础、城市/区域尺度、设计草图、情境分析与跨学科城市发展兴趣。",
        requirements: "建筑学本科或等值训练；作品集、CV、动机信、学历与成绩材料，并对申请中使用 AI 的位置与用途作简短声明；2027 格式发布后再复核。",
        interview: "必需（入围后）：通过第一阶段的申请者进入第二阶段线上面试。",
        warning: "如果目标是传统建筑师训练，应优先评估 Architecture major。",
        url: "https://www.aalto.fi/en/study-options/masters-programme-in-urban-studies-and-planning-msc-in-architecture"
      }
    ]
  },
  {
    id: "tampere",
    name: "Tampere University",
    cn: "坦佩雷大学",
    city: "坦佩雷",
    country: "芬兰",
    position: "以建筑设计同时回应环境、社会与文化层面的可持续性，并关注设计过程及其实际结果。",
    programs: [{
      id: "tampere-sustainable",
      name: "Sustainable Architecture",
      degree: "MSc Architecture",
      duration: "2 年 · 120 ECTS",
      language: "英语",
      tuition: "€12,000 / 年（最新：2026 入学）",
      deadline: "最新：2025.12.15—2026.01.05 · 2027 待公布",
      status: "最新公开：2026 · 2027 待更新",
      tags: ["可持续", "再利用", "气候适应"],
      intro: "以整体可持续性与联合国可持续发展目标为框架，将生态、社会和文化维度贯穿设计过程与结果；并非只训练建筑节能技术。",
      suitable: "有再利用、住房、公共建筑、材料生命周期或气候适应项目的建筑本科生。",
      portfolio: "证明环境策略怎样改变空间、结构、材料、生命周期和使用方式，避免仅使用绿色标签。",
      requirements: "相关建筑学位、英语证明及 Studyinfo 当轮要求的补充材料。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
      warning: "旧有 12 月至 1 月的日期不能当作 2027 已公布截止。",
      url: "https://www.tuni.fi/en/tau/masters-programmes/sustainable-architecture-architecture"
    }]
  },
  {
    id: "oulu",
    name: "University of Oulu",
    cn: "奥卢大学",
    city: "奥卢",
    country: "芬兰",
    position: "以城市与公共建筑设计为主轴，结合建筑细部、北欧材料、照明、室内及建筑理论研究的综合专业教育。",
    programs: [{
      id: "oulu-architecture",
      name: "Architecture",
      degree: "Master's in Architecture",
      duration: "2 年",
      language: "英语",
      tuition: "€14,000 / 年",
      deadline: "2027.01.07—01.21",
      status: "2027 已公布",
      tags: ["建筑设计", "公共建筑", "木构"],
      intro: "训练城市区域与空间、公共建筑、建筑及城市构造细部设计，并纳入北欧材料（包括木材）、建筑照明、室内设计和建筑理论研究。",
      suitable: "愿意研究寒地生活、气候、木构、社区与技术实现的建筑本科生。",
      portfolio: "用剖面、围护、采光、季节环境与材料逻辑证明设计能力。",
      requirements: "相关建筑本科与英语证明；最终以 Studyinfo 当轮页面为准。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
      warning: "第二年 40% tuition waiver 不是标准学费，不能把减免后的 €9,800 作为报价。",
      url: "https://www.oulu.fi/en/apply/masters-architecture"
    }]
  },
  {
    id: "kth",
    name: "KTH Royal Institute of Technology",
    cn: "瑞典皇家理工学院",
    city: "斯德哥尔摩",
    country: "瑞典",
    position: "作为五年制建筑师教育的高级阶段，以 studio 推进个人建筑能力、专业判断与可持续建成环境议题。",
    programs: [{
      id: "kth-architecture",
      name: "Architecture",
      degree: "MSc Architecture",
      duration: "2 年 · 120 ECTS",
      language: "英语",
      tuition: "SEK 600,000 / 全项目",
      deadline: "2027.01.15 · 材料 02.01",
      status: "2027 已公布",
      tags: ["建筑设计", "技术整合", "城市"],
      intro: "通过三学期课程与设计 studio 深化建筑能力和判断，末学期完成学位项目；可持续发展、城市与建筑品质贯穿培养，而非单独的技术专项。",
      suitable: "能同时处理空间组织、城市尺度和技术实现的建筑本科生。",
      portfolio: "以完整项目说明设计命题与技术、环境系统之间的关系，避免堆叠竞赛效果图。",
      requirements: "相应建筑本科及 Swedish national admissions 的通用与项目条件。",
        interview: "官网未列为常规环节：以申请材料与作品集评审为主；2027 简章发布后复核。",
      warning: "学费以瑞典克朗公布，不用未标日期的欧元换算值作固定报价。",
      url: "https://www.kth.se/en/studies/master/architecture/msc-architecture-1.48041"
    }]
  },
  {
    id: "chalmers",
    name: "Chalmers University of Technology",
    cn: "查尔姆斯理工大学",
    city: "哥德堡",
    country: "瑞典",
    position: "在专业建筑设计与社会—生态转型之间提供两条清晰路径。",
    programs: [
      {
        id: "chalmers-aud",
        name: "Architecture and Urban Design",
        degree: "MSc",
        duration: "2 年 · 120 ECTS",
        language: "英语",
        tuition: "最新费用页：2026/27 · 2027 金额待确认",
        deadline: "最新：2025.10.16—2026.01.15 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["建筑设计", "城市设计", "专业实践"],
        intro: "以设计为主导，同时兼具实践、学术与理论训练；核心内容包括建筑设计与转化、复杂建筑任务、建筑实验、建造和城市设计，并从可持续视角展开。",
        suitable: "希望深化专业建筑与城市设计、具有完整空间表达能力的申请者。",
        portfolio: "突出不同尺度之间的连续性，以及空间、构造和城市判断的整合。",
        requirements: "180 ECTS 等值本科及项目特定先修、英语和作品集要求。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "不要以泛称 Architecture MSc 代替具体项目名。",
        url: "https://www.chalmers.se/en/education/find-masters-programme/architecture-and-urban-design-msc/"
      },
      {
        id: "chalmers-apbs",
        name: "Architecture and Planning Beyond Sustainability",
        degree: "MSc",
        duration: "2 年 · 120 ECTS",
        language: "英语",
        tuition: "最新费用页：2026/27 · 2027 金额待确认",
        deadline: "最新：2025.10.16—2026.01.15 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["可持续", "社会生态", "规划"],
        intro: "把可持续建筑与城市设计设为全部课程的共同主轴，重点涉及建筑发展、设计项目、建造、郊区设计与可持续发展方法。",
        suitable: "能形成研究问题，处理资源、利益相关者、治理与空间后果的申请者。",
        portfolio: "以真实情境、证据与设计后果建立论证，不做抽象的绿色未来。",
        requirements: "相关建筑、工程、技术或科学本科，并满足项目特定条件。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "与 A&UD 的动机和作品集重点必须区分。",
        url: "https://www.chalmers.se/en/education/find-masters-programme/architecture-and-planning-beyond-sustainability-msc/"
      }
    ]
  },
  {
    id: "lund",
    name: "Lund University",
    cn: "隆德大学",
    city: "隆德",
    country: "瑞典",
    position: "从全面建筑训练到数字研究、可持续城市设计的多入口体系。",
    programs: [
      {
        id: "lund-architecture",
        name: "Architecture",
        degree: "MSc",
        duration: "2 年 · 120 ECTS",
        language: "英语 · English 6",
        tuition: "SEK 540,000 / 全项目（最新：2026 入学）",
        deadline: "最新：2026 轮 01.15 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["建筑设计", "材料建造", "社会议题"],
        intro: "以建筑设计回应环境变化、住房短缺和城市隔离等当代问题，强调材料性、结构与空间秩序的整合；第三学期可进入居住与空间、城市庇护、文化遗产建筑、可持续城市动力或空间实验方向。",
        suitable: "希望继续全面专业建筑训练的建筑本科生。",
        portfolio: "单一数字 PDF；平立剖、构造与过程必须完整，以当轮 10MB 等格式指令为准。",
        requirements: "建筑学本科或等同背景、个人数字作品集、statement 与 English 6。",
        interview: "官网未列为常规环节：以申请材料与作品集评审为主；2027 简章发布后复核。",
        warning: "以 SEK 收费，旧欧元换算不能直接作为报价。",
        url: "https://www.lunduniversity.lu.se/study/architecture-masters-programme-TAMAR"
      },
      {
        id: "lund-daef",
        name: "Digital Architecture and Emergent Futures",
        degree: "MSc",
        duration: "2 年 · 120 ECTS",
        language: "英语 · English 6",
        tuition: "SEK 540,000 / 全项目（最新：2026 入学）",
        deadline: "最新：2026 轮 01.15 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["计算设计", "数字制造", "材料研究"],
        intro: "聚焦正在形成的数字设计流程，训练编程、参数化建模，以及 3D 打印和机器人等数字制造方法，并与 bioDigital Matter 和 Construction Robotics 研究协作。",
        suitable: "已有计算设计、材料实验、制造或批判技术叙事的建筑申请者。",
        portfolio: "说明数字工具背后的材料、构造与环境问题，参数化形式不能替代建筑结果。",
        requirements: "相关建筑背景、作品集、statement 与 English 6。",
        interview: "官网未列为常规环节：以申请材料与作品集评审为主；2027 简章发布后复核。",
        warning: "这是明确的数字研究方向，不应混同为通用 M.Arch。",
        url: "https://www.lunduniversity.lu.se/study/digital-architecture-and-emergent-futures-masters-programme-TAAEF"
      },
      {
        id: "lund-sud",
        name: "Sustainable Urban Design",
        degree: "MSc",
        duration: "2 年",
        language: "英语 · English 6",
        tuition: "SEK 540,000 / 全项目（最新：2026 入学）",
        deadline: "最新：2026 轮 01.15 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["城市设计", "可持续", "跨学科"],
        intro: "把建筑设计与可持续原则结合，从社会、经济和环境三方面训练人本城市设计，并将宜居性、社区营造和社会可持续目标转化为具体空间方案。",
        suitable: "作品集中有城市、景观、规划或社会空间连续研究的申请者。",
        portfolio: "突出尺度转换、田野证据、空间规则与城市策略。",
        requirements: "相关本科、个人数字作品集与 English 6。",
        interview: "官网未列为常规环节：以申请材料与作品集评审为主；2027 简章发布后复核。",
        warning: "跨学科友好不等于没有空间设计门槛。",
        url: "https://www.lunduniversity.lu.se/study/sustainable-urban-design-masters-programme-TASUD"
      }
    ]
  },
  {
    id: "umea",
    name: "Umeå School of Architecture",
    cn: "于默奥建筑学院",
    city: "于默奥",
    country: "瑞典",
    position: "在艺术与科学之间，以实验性 studio 研究可持续建筑、社会公正城市及建筑实践的替代路径。",
    programs: [{
      id: "umea-aud",
      name: "Architecture and Urban Design",
      degree: "Artistic Master's Degree",
      duration: "2 年 · 120 ECTS",
      language: "英语",
      tuition: "SEK 473,600 / 全项目（2027 官网）",
      deadline: "2027.01.15",
      status: "2027 已公布",
      tags: ["实验建筑", "社会空间", "设计制作"],
      intro: "把 studio 作为实验室，围绕气候变化、不平等、迁移等生态与社会危机开展跨尺度设计，并通过技术实验、原型、足尺建造和空间介入检验方案。",
      suitable: "能以空间、社会、艺术与制作形成独立论述的建筑本科生。",
      portfolio: "保留清晰的建筑设计能力，同时呈现批判观察、手作、过程和个人方法。",
      requirements: "建筑本科或等同背景；学术材料走统一平台，portfolio 按学校方式单独提交。",
        interview: "官网未列为常规环节：以申请材料与作品集评审为主；2027 简章发布后复核。",
      warning: "授予艺术硕士，须与瑞典五年制专业 Architecture Programme 区分。",
      url: "https://www.umu.se/en/umea-school-of-architecture/education/programmes/masters-programme-in-architecture-and-urban-design/"
    }]
  },
  {
    id: "aarhus",
    name: "Aarhus School of Architecture",
    cn: "奥胡斯建筑学院",
    city: "奥胡斯",
    country: "丹麦",
    position: "以两年英语艺术型建筑硕士延续专业建筑训练，具体 studio 和研究主题按年度教学安排展开。",
    programs: [{
      id: "aarhus-architecture",
      name: "Architecture",
      degree: "Master in Architecture",
      duration: "2 年",
      language: "英语路径 · 当轮确认",
      tuition: "€18,000 / 年（最新：2026 入学）",
      deadline: "最新 call：2026 入学 · 2027 待发布",
      status: "最新公开：2026 · 2027 待更新",
      tags: ["建筑设计", "艺术实践", "专业实践"],
      intro: "英语项目与丹麦语建筑硕士在培养本质上相同，以艺术型专业建筑教育和 studio 学习为核心；具体方向需依当年课程与 studio 核对。",
      suitable: "有建筑本科、愿意把实验与现实议题共同推进且资金规划充分的申请者。",
      portfolio: "把场地阅读、策略、建筑空间与技术表达压缩为清晰主线。",
      requirements: "依年度 application guidelines 与 portfolio requirements 核查。",
        interview: "官网未列申请人面试：所谓第二轮是学校内部进一步评审；2027 年度指南发布后复核。",
      warning: "RIBA Part 2 适用性须按入学年度重新核实；学校不提供校内 financial aid。",
      url: "https://aarch.dk/en/full-degree-student-admission/"
    }]
  },
  {
    id: "kadk",
    name: "Royal Danish Academy",
    cn: "丹麦皇家建筑、设计与艺术学院",
    city: "哥本哈根",
    country: "丹麦",
    position: "以具体 studio 为核心，在建筑、城市、极端环境、材料与转型之间选择方向。",
    programs: [
      {
        id: "kadk-critical-sustainability",
        name: "Political Architecture: Critical Sustainability",
        degree: "MA Architecture",
        duration: "2 年",
        language: "英语",
        tuition: "最新公开：2026 call · 2027 学费待公布",
        deadline: "最新：2026.03.01 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["批判性可持续", "政治建筑", "社会生态"],
        intro: "从政治、资源与社会关系审视可持续性，同时强调实践、材料与建造方法，使批判立场落实为可实施的建筑设计。",
        suitable: "具备建筑本科、研究能力与社会—生态议题项目的申请者。",
        portfolio: "让研究问题落到现状阅读、空间决策、材料和构造，不只呈现立场。",
        requirements: "国家认可学校的 Bachelor in Architecture 或 architectural studies，及当轮完整材料。",
        interview: "官网未列为常规环节：以申请材料与作品集评审为主；2027 简章发布后复核。",
        warning: "studio 名称、开放状态、名额与费用必须按 2027 admissions portal 复核。",
        url: "https://kglakademi.dk/en/admission-master"
      },
      {
        id: "kadk-extreme",
        name: "Architecture and Extreme Environments",
        degree: "MA Architecture",
        duration: "2 年",
        language: "英语",
        tuition: "最新公开：2026 call · 2027 学费待公布",
        deadline: "最新：2026.03.01 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["极端环境", "气候", "原型"],
        intro: "以极端环境为具体场地条件，结合实地与环境研究、建筑实验和原型设计，探索建筑对气候及地域限制的回应。",
        suitable: "有气候、地域、材料实验或实地研究经验的建筑申请者。",
        portfolio: "呈现环境证据如何驱动剖面、围护、构造与使用方式。",
        requirements: "建筑或 architectural studies 本科；按年度 studio 开放情况申请。",
        interview: "官网未列为常规环节：以申请材料与作品集评审为主；2027 简章发布后复核。",
        warning: "不要只把极端环境当作视觉题材。",
        url: "https://kglakademi.dk/en/admission-master"
      },
      {
        id: "kadk-urbanism",
        name: "Urbanism & Societal Change",
        degree: "MA Architecture",
        duration: "2 年",
        language: "英语",
        tuition: "最新公开：2026 call · 2027 学费待公布",
        deadline: "最新：2026.03.01 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["城市", "社会转型", "公共性"],
        intro: "研究社会变化如何作用于城市及其空间实践，以城市设计和跨尺度策略回应城市化、公共生活与制度转型。",
        suitable: "有城市、住房、迁移、治理或公共空间项目的建筑申请者。",
        portfolio: "强化城市研究、图纸尺度和空间原型之间的连续性。",
        requirements: "建筑或 architectural studies 本科；具体要求按当年 studio。",
        interview: "官网未列为常规环节：以申请材料与作品集评审为主；2027 简章发布后复核。",
        warning: "跨尺度研究不能替代建筑和空间表达。",
        url: "https://royaldanishacademy.com/en/programme/urbanism-and-societal-change"
      },
      {
        id: "kadk-computation",
        name: "Computation in Architecture",
        degree: "MA Architecture",
        duration: "2 年",
        language: "英语",
        tuition: "€9,000 / 学期（最新：2026/27 非欧盟）",
        deadline: "最新：2026.03.01 · 2027 待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["计算设计", "生物材料", "机器人制造"],
        intro: "以批判方式研究当代建模与制造技术，重点包括高级及生成式建模、活体与生物材料，以及机器人制造。",
        suitable: "有计算设计、数字制造、材料实验或技术研究基础的建筑申请者。",
        portfolio: "说明计算方法如何改变空间、材料、构造和生产过程，避免只展示形式生成。",
        requirements: "国家认可建筑学院的 Bachelor in Architecture 或 architectural studies，并满足当轮英语及申请材料要求。",
        interview: "官网未列为常规环节：以申请材料与作品集评审为主；2027 简章发布后复核。",
        warning: "数字工具必须服务于清晰的建筑问题和可验证的设计结果。",
        url: "https://royaldanishacademy.com/en/master-computation-in-architecture"
      },
      {
        id: "kadk-furniture",
        name: "Furniture Design: Products, Materials and Contexts",
        degree: "MA Architecture · Architecture pathway",
        duration: "2 年",
        language: "英语",
        tuition: "€9,000 / 学期（最新：2026/27 非欧盟）",
        deadline: "最新：2026.03.01 · 2027 待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["家具设计", "材料", "制作"],
        intro: "在家具、空间、材料和工业产品设计之间展开，以制作、材料理解及具体使用情境连接建筑尺度与产品尺度。",
        suitable: "建筑或设计背景中具有家具、室内、构件、材料及实体制作经验的申请者。",
        portfolio: "突出尺度、人体、材料、连接方式、原型和使用测试，并清楚标明个人制作贡献。",
        requirements: "建筑申请者按 MA Architecture 路径申请；须满足相应建筑本科及当轮材料要求。",
        interview: "官网未列为常规环节：以申请材料与作品集评审为主；2027 简章发布后复核。",
        warning: "这是建筑与设计交叉项目，申请时必须选择正确的 Architecture programme application。",
        url: "https://royaldanishacademy.com/en/programme/furniture-design"
      },
      {
        id: "kadk-spatial-design",
        name: "Spatial Design – Architecture, Design and Interiors",
        degree: "MA Architecture · Architecture pathway",
        duration: "2 年",
        language: "英语",
        tuition: "€9,000 / 学期（最新：2026/27 非欧盟）",
        deadline: "最新：2026.03.01 · 2027 待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["空间设计", "室内", "跨尺度"],
        intro: "位于建筑、设计与室内的交界，研究空间、物件、材料和身体经验之间的关系，并处理既有空间的转化。",
        suitable: "有建筑、室内、展陈、装置或空间—物件跨尺度研究的申请者。",
        portfolio: "通过平剖、节点、材料样本、模型和使用情境证明空间设计能力。",
        requirements: "建筑申请者按 MA Architecture 路径申请；须满足相应建筑本科及当轮材料要求。",
        interview: "官网未列为常规环节：以申请材料与作品集评审为主；2027 简章发布后复核。",
        warning: "不能只提交装置或氛围图，需要显示建筑尺度、技术和空间组织能力。",
        url: "https://royaldanishacademy.com/en/programme/spatial-design-0"
      },
      {
        id: "kadk-spatial-ecologies",
        name: "Spatial Ecologies",
        degree: "MA Architecture",
        duration: "2 年",
        language: "主要英语 · Kalundborg 校区",
        tuition: "€9,000 / 学期（最新：2026/27 非欧盟）",
        deadline: "最新：2026.03.01 · 2027 待公布",
        status: "2026 新项目 · 2027 待更新",
        tags: ["空间生态", "资源流", "工业共生"],
        intro: "把建筑、城市与景观视为嵌入材料、生态和文化系统的实践，通过实地研究、研究型设计和足尺实验处理资源稀缺、生态转型、生物制造与工业共生。",
        suitable: "关注景观城市主义、循环资源、生物材料、产业转型或社会—环境不稳定性的建筑申请者。",
        portfolio: "建立场地调查、资源流、跨尺度分析、材料实验与具体空间提案之间的连续性。",
        requirements: "建筑或 architectural studies 本科；项目在 Kalundborg 与哥本哈根建筑硕士分开申请。",
        interview: "官网未列为常规环节：以申请材料与作品集评审为主；2027 简章发布后复核。",
        warning: "校区、申请入口与教学安排须按 2027 Kalundborg 招生页面单独确认。",
        url: "https://royaldanishacademy.com/en/programme/spatial-ecologies"
      },
      {
        id: "kadk-strategic-design",
        name: "Strategic Design & Entrepreneurship – Architecture",
        degree: "MA Architecture · Architecture pathway",
        duration: "2 年",
        language: "英语",
        tuition: "€9,000 / 学期（最新：2026/27 非欧盟）",
        deadline: "最新：2026.03.01 · 2027 待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["战略设计", "创新", "创业"],
        intro: "连接建筑与设计方法、战略创新和创业实践，研究如何在组织、市场及社会系统中形成并实施新的解决方案。",
        suitable: "希望把空间与设计能力延伸到创新策略、组织合作、服务或创业实践的建筑申请者。",
        portfolio: "除建筑成果外，呈现问题定义、利益相关者、协作过程、验证和实施逻辑。",
        requirements: "建筑申请者按 MA Architecture 路径申请；须满足相应建筑本科及当轮材料要求。",
        interview: "官网未列为常规环节：以申请材料与作品集评审为主；2027 简章发布后复核。",
        warning: "项目并非传统建筑 studio 路径，职业目标应与战略设计和创业方向一致。",
        url: "https://royaldanishacademy.com/en/programme/strategic-design-entrepreneurship"
      }
    ]
  },
  {
    id: "aho",
    name: "Oslo School of Architecture and Design",
    cn: "奥斯陆建筑与设计学院",
    city: "奥斯陆",
    country: "挪威",
    position: "长学制、强 studio 与自主 diploma 的专业建筑师培养后段。",
    programs: [{
      id: "aho-architecture",
      name: "Architecture",
      degree: "Master of Architecture",
      duration: "2.5 年 · 150 ECTS",
      language: "英语路径 · 当轮确认",
      tuition: "NOK 150,000 / 年（最新：2026/27 非欧盟）",
      deadline: "最新：2025.12.05—2026.02.02 · 2027 待公布",
      status: "最新公开：2026 · 2027 待更新",
      tags: ["建筑设计", "自主研究", "跨学科"],
      intro: "连接艺术、人文、社会科学与工程方法，并以自主 diploma 完成专业训练。",
      suitable: "已有扎实建筑本科训练、能够建立研究立场并持续迭代的成熟申请者。",
      portfolio: "证明连续的建筑教育基础与独立推进问题的能力；单一 PDF 格式按当轮要求。",
      requirements: "建筑本科或等值 180 ECTS、英语与 portfolio。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
      warning: "项目为 2.5 年而不是常见两年制；名额与学费不能固定承诺。",
      url: "https://www.aho.no/english/studies/programmes/master-of-architecture/admission/"
    }]
  },
  {
    id: "bas",
    name: "Bergen School of Architecture",
    cn: "卑尔根建筑学院",
    city: "卑尔根",
    country: "挪威",
    position: "以整学期综合课程连接建筑、设计、艺术、理论与建造，并以学生自主命题的 diploma 收束专业训练。",
    programs: [{
      id: "bas-architecture",
      name: "Architecture · Year 4 entry",
      degree: "Master in Architecture",
      duration: "后两年 · 每学期 30 ECTS",
      language: "英语",
      tuition: "NOK 325,292 / 年（最新：2026/27 非欧盟）",
      deadline: "最新：2026.04.15 · 2027 待公布",
      status: "最新公开：2026 · 2027 待更新",
      tags: ["实验建筑", "设计建造", "批判实践"],
      intro: "进入五年制建筑教育的第 4、5 年，以 semester package 整合建筑、理论、艺术与建造。",
      suitable: "已有建筑本科、作者性强，希望在自由 studio 深化明确议题的申请者。",
      portfolio: "明确个人角色、过程、模型、材料、图纸与最终论证。",
      requirements: "至少完成建筑本科；成绩单、作品集及当轮申请材料。",
        interview: "Year 4 现行申请说明未列面试；一年级申请的面试规则不适用于本项目。",
      warning: "不是面向所有本科背景的普通两年制转换硕士；非欧盟费用较高且无奖学金。",
      url: "https://bas.org/en/opptak/"
    }]
  },
  {
    id: "mendrisio",
    name: "USI Accademia di Architettura",
    cn: "门德里西奥建筑学院",
    city: "门德里西奥",
    country: "瑞士",
    position: "高密度建筑文化、历史与当代设计教育，建立在意大利语语境中。",
    programs: [{
      id: "mendrisio-architecture",
      name: "Architecture",
      degree: "Master in Architecture",
      duration: "2 年 · 120 ECTS + 9 个月实习",
      language: "主语言意大利语 · 部分英语",
      tuition: "CHF 4,000 / 学期（最新：2026/27 国际生）",
      deadline: "最新：2026.02.15（需签证）· 2027 待公布",
      status: "最新公开：2026/27 · 非全英文",
      tags: ["建筑文化", "历史理论", "设计批评"],
      intro: "优势在建筑史、理论、领土与 studio 密度，但主教学语言是意大利语。",
      suitable: "已有或愿长期投入意大利语，并对建筑文化、城市与设计批评有明确兴趣的申请者。",
      portfolio: "强调历史与设计的互相转译、强有力的平立剖以及实体和构造推理。",
      requirements: "建筑本科；成绩、课程表、CV、动机、作品集及推荐信等。",
        interview: "可能（特定申请者）：部分需签证类别的入选申请者可能被要求参加约 5–10 分钟 Skype 面试。",
      warning: "不能列入“只需英语即可完成”的项目名单。",
      url: "https://www.arc.usi.ch/en/study-architecture/master/architecture"
    }]
  },
  {
    id: "florence",
    name: "University of Florence",
    cn: "佛罗伦萨大学",
    city: "佛罗伦萨",
    country: "意大利",
    position: "以建筑设计全过程为核心，综合建筑与城市转型、技术创新、景观及建筑遗产保护。",
    programs: [{
      id: "florence-architectural-design",
      name: "Architecture · Architectural Design",
      degree: "LM-4 second-cycle degree",
      duration: "通常 2 年",
      language: "英语 B2 路径",
      tuition: "最新费用资料：2025/26 · 2027 待公布",
      deadline: "最新 international call：2025/26 · 2027 待发布",
      status: "最新公开：2025/26 · 2027 待更新",
      tags: ["建筑设计", "城市转型", "技术整合"],
      intro: "训练从概念到施工现场的建筑设计全过程，并处理历史与现代城市系统中的建筑和城市转型、当代建造技术、材料、环境与经济可持续性及遗产保护。",
      suitable: "建筑本科扎实，并有改造、修复、历史环境或理论—设计项目的申请者。",
      portfolio: "展示历史条件如何进入空间、图纸与材料判断，避免仅把城市当作图像风格。",
      requirements: "建筑或相当背景、英文 B2；名额、作品集和面试按年度 call。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
      warning: "不要与校内一年制 professional Master course 混淆；旧学费只是估算。",
      url: "https://www.unifi.it/en/study-us/degree-programmes/international-courses/international-degree-programmes"
    }]
  },
  {
    id: "iuav",
    name: "Università Iuav di Venezia",
    cn: "威尼斯建筑大学",
    city: "威尼斯",
    country: "意大利",
    position: "以威尼斯的建筑、城市、景观与遗产作为当代实验语境。",
    programs: [{
      id: "iuav-architecture",
      name: "Architecture",
      degree: "MA Architecture",
      duration: "2 年",
      language: "英语",
      tuition: "最高约 €2,806 / 年（最新：2026/27）",
      deadline: "最新：2026.02.23 截止（2026/27）· 2027 待发布",
      status: "最新公开：2026/27 · 2027 待更新",
      tags: ["建筑设计", "城市", "遗产改造"],
      intro: "全英文建筑硕士，将城市与历史环境研究和当代空间设计结合。",
      suitable: "有城市剖析、改造、修复或历史环境设计能力的建筑本科生。",
      portfolio: "用图纸和材料判断说明历史条件怎样转化为设计策略。",
      requirements: "建筑本科或经评估的等同背景；按年度 call 提交学历、课程、语言和作品集。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
      warning: "学费是最高额参考，语言考试与截止均以 2027 call 为准。",
      url: "https://www.iuav.it/en/didattica/lauree-magistrali/architecture"
    }]
  },
  {
    id: "polito",
    name: "Politecnico di Torino",
    cn: "都灵理工大学",
    city: "都灵",
    country: "意大利",
    position: "以建造、城市、遗产或可持续形成明确的专业方向选择。",
    programs: [
      {
        id: "polito-construction-city",
        name: "Architecture Construction City",
        degree: "MSc Architecture",
        duration: "2 年",
        language: "按 curriculum · 英语路径需 B2",
        tuition: "最新 fee guide：2026/27 · 2027 待公布",
        deadline: "最新：2025.12.19—2026.01.29（2026/27）· 2027 待发布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["建造", "城市", "建筑设计"],
        intro: "强调建筑、建造和城市之间的综合能力。",
        suitable: "图纸、构造、城市分析都较完整，且能证明课程匹配度的建筑本科生。",
        portfolio: "呈现从城市条件到建筑与构造的连续推演。",
        requirements: "学位、成绩、课程 syllabus、CV、语言、作品集与学历认证材料。",
        interview: "通常不要求：非意大利学历申请以材料/作品集评审；特定资格或成绩路径可能另有测试/面谈。",
        warning: "先确认具体 curriculum 的授课语言；不能把双语要求套给全部项目。",
        url: "https://www.polito.it/en/education/applying-studying-graduating/admissions-and-enrolment/master-s-degree-programmes/applicants-with-a-non-italian-qualification"
      },
      {
        id: "polito-sustainability",
        name: "Architecture for Sustainability",
        degree: "MSc Architecture",
        duration: "2 年",
        language: "英语路径需 B2",
        tuition: "最新 fee guide：2026/27 · 2027 待公布",
        deadline: "最新：2025.12.19—2026.01.29（2026/27）· 2027 待发布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["可持续", "更新", "环境性能"],
        intro: "把环境、更新、性能与建筑设计结合，方向明确且重视技术和课程先修。",
        suitable: "有环境策略、既有建筑更新或性能—空间整合项目的申请者。",
        portfolio: "让性能证据、材料与空间结果形成因果链。",
        requirements: "相关本科和课程匹配；英语 B2 及项目当轮材料。",
        interview: "通常不要求：非意大利学历申请以材料/作品集评审；特定资格或成绩路径可能另有测试/面谈。",
        warning: "全英文项目不额外要求意大利语 B2。",
        url: "https://www.polito.it/en/education/applying-studying-graduating/admissions-and-enrolment/master-s-degree-programmes/applicants-with-a-non-italian-qualification"
      },
      {
        id: "polito-heritage",
        name: "Architecture for Heritage",
        degree: "MSc Architecture",
        duration: "2 年",
        language: "按 curriculum 核查",
        tuition: "最新 fee guide：2026/27 · 2027 待公布",
        deadline: "最新：2025.12.19—2026.01.29（2026/27）· 2027 待发布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["遗产", "修复", "建筑历史"],
        intro: "聚焦历史建成环境、修复与转化，要求设计和知识结构同时连续。",
        suitable: "有建筑史、测绘、修复、再利用或遗产介入项目的申请者。",
        portfolio: "用现状、病理或历史研究支持具体空间和构造决策。",
        requirements: "相关建筑背景、课程先修及具体语言配置。",
        interview: "通常不要求：非意大利学历申请以材料/作品集评审；特定资格或成绩路径可能另有测试/面谈。",
        warning: "必须读取对应 academic regulations，不能只按学校总名申请。",
        url: "https://www.polito.it/en/education/applying-studying-graduating/admissions-and-enrolment/master-s-degree-programmes/applicants-with-a-non-italian-qualification"
      }
    ]
  },
  {
    id: "iceland",
    name: "Iceland University of the Arts",
    cn: "冰岛艺术大学",
    city: "雷克雅未克",
    country: "冰岛",
    position: "把建筑教育视为批判研究、社会意识、集体想象与修复共同空间的行动，并以冰岛作为设计实验室。",
    programs: [{
      id: "iceland-march",
      name: "Architecture",
      degree: "M.Arch",
      duration: "2 年 · 120 ECTS",
      language: "英语",
      tuition: "ISK 4,500,000 / 年（最新：2026/27 非 EEA）",
      deadline: "最新：2026.03.02 · 2027 待公布",
      status: "最新公开：2026 · 2027 待更新",
      tags: ["设计研究", "社会生态", "艺术实践"],
      intro: "以设计 studio 为骨架，在冰岛这一具体实验场中培养批判思维、环境觉察、自我反思、想象与行动能力，回应气候危机、社会不平等、城市化和生物多样性等议题。",
      suitable: "有原创空间方法、材料实验和环境观察的建筑申请者。",
      portfolio: "呈现独立探索和可落地的建筑尺度证据，不把冰岛仅当作视觉题材。",
      requirements: "建筑本科或足够建筑训练、作品集和项目申请文件；英语要求按当轮。",
        interview: "必需（入围后）：学校会邀请入围申请者参加面试。",
      warning: "非 EEA 申请者 2026/27 建筑学费为 ISK 4,500,000/年；ISK 100,000 是适用于 EEA 等类别的年度注册费，不是非 EEA 学费。学校不提供学费或生活费奖学金。",
      url: "https://www.lhi.is/en/namsleid/architects-include/"
    }]
  },
  {
    id: "archip",
    name: "ARCHIP",
    cn: "布拉格建筑学院",
    city: "布拉格",
    country: "捷克",
    position: "小规模国际 studio 与高频导师反馈并重的英语建筑专业路径。",
    programs: [{
      id: "archip-master",
      name: "Architecture and Urbanism",
      degree: "Master",
      duration: "2 年 · 4 学期",
      language: "英语 · IELTS 6.5 / TOEFL iBT 79 / CEFR C1",
      tuition: "€4,500 / 学期（官网当前价）",
      deadline: "最新：EU 2026.07.31 · 非 EU/2027 待确认",
      status: "最新公开：2026/27 · 2027 待更新",
      tags: ["建筑实践", "城市", "小班工作室"],
      intro: "整合设计、历史、理论、研究与专业实践，研究生规模小、导师讨论密度高。",
      suitable: "需要高频反馈、希望强化专业设计与表达的建筑本科生。",
      portfolio: "单一 PDF，不超过 10MB、15 张 A3 横向页面、最多 5 个项目；至少 2 个个人项目、至少 1 个项目体现结构与技术能力，事务所项目最多 2 个。",
      requirements: "建筑、规划、景观建筑或土木工程本科；CV、成绩/学位、英语证明、作品集，以及 750–1,000 词项目分析 essay。",
        interview: "可能：材料审核后，学校可能要求申请者参加线上面试。",
      warning: "非 EU 与签证申请者应提前确认；旧 2 月截止不再可靠。",
      url: "https://www.archip.eu/master-programme/"
    }]
  },
  {
    id: "liechtenstein",
    name: "University of Liechtenstein",
    cn: "列支敦士登大学",
    city: "瓦杜兹",
    country: "列支敦士登",
    position: "以气候变化与资源稀缺为总问题，通过小班 studio、足尺建造及研究—实践连接培养可持续建筑能力。",
    programs: [{
      id: "liechtenstein-architecture",
      name: "Architecture",
      degree: "MSc Architecture",
      duration: "2 年 · 120 ECTS",
      language: "英语",
      tuition: "CHF 1,250 / 学期（最新：2026/27，其他国籍）",
      deadline: "最新：EU/EEA/CH 2026.07.31 · 非 EU/2027 待确认",
      status: "最新公开：2026/27 · 2027 待更新",
      tags: ["可持续", "足尺建造", "建筑设计"],
      intro: "以小班 studio 和 1:1 实作为基础，可选 Craft & Structure、Sustainable Design、Built Heritage & Upcycling、Urban Design & Spatial Development、Housing & Society 五个非强制 Major。",
      suitable: "希望紧密导师沟通，并有材料、结构、环境或地域设计作品的建筑本科生。",
      portfolio: "突出专注的建筑问题、图纸、模型与材料工作，并说明与可选 major 的关联。",
      requirements: "建筑或相关领域本科、至少 180 ECTS；英语 B2、动机信和包含本科毕业设计的项目作品集。国籍对应费用与签证截止须核查。",
        interview: "官网未列为常规环节：按学历、动机信、英语证明与作品集评审；如招生办公室另行通知再准备。",
      warning: "非 EU 截止通常早于 EU；语言证书与具体 major 每年核查。",
      url: "https://www.uni.li/en/studies/study-programmes/msc-architecture"
    }]
  },
  {
    id: "eth-zurich",
    name: "ETH Zürich",
    cn: "苏黎世联邦理工学院",
    city: "苏黎世",
    country: "瑞士",
    position: "以设计 studio 为核心，结合历史与理论、技术、建造、景观和城市设计的德语专业建筑教育。",
    programs: [{
      id: "eth-architecture",
      name: "Architecture",
      degree: "MSc ETH in Architecture",
      duration: "2 年 · 120 ECTS + 6 个月实践",
      language: "德语 · C1",
      tuition: "CHF 2,190 / 学期 + 杂费",
      deadline: "最新官方：2025.11.01—11.30（2026 入学）· 2027 待公布",
      status: "最新公开：2026 · 2027 待更新",
      tags: ["建筑设计", "技术整合", "历史理论", "城市"],
      intro: "以设计 studio 为核心，配合历史与理论、技术、建造史与保护、景观和城市设计课程，最终完成 Master’s thesis；具体 studio 主题随学期变化。",
      suitable: "建筑本科课程完整、设计与技术基本功强，已具备或能够按期取得德语 C1，并能完成实践要求的申请者。",
      portfolio: "A4 数字 PDF、最多 15 页；3 个在校项目且至少 2 个为设计项目，突出设计表达、场地回应及材料和构造尺度的资源判断。",
      requirements: "建筑本科或等值教育；申请截止前提交认可的德语 C1；国际学历接受课程等值审查，取得学位前须证明至少 6 个月建筑或建造行业实践。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
      warning: "核心 Architecture MSc 不能仅凭英语规划。部分课程或考试可用英语，不代表英语证书可替代德语 C1；Landscape Architecture 是另一专业。",
      url: "https://ethz.ch/en/studies/master/application/master-architektur.html"
    }]
  },
  {
    id: "epfl",
    name: "EPFL",
    cn: "洛桑联邦理工学院",
    city: "洛桑",
    country: "瑞士",
    position: "以建筑、城市和领土尺度的设计为核心，在 ENAC 体系中综合人文、结构、技术与环境科学。",
    programs: [{
      id: "epfl-architecture",
      name: "Architecture",
      degree: "MSc in Architecture",
      duration: "2 年 · 120 ECTS + 12 个月既往实践",
      language: "法语 / 英语 · 双语",
      tuition: "CHF 2,240 / 学期总账单",
      deadline: "最新官方节奏：12.15 / 03.31 · 2027 年份待确认",
      status: "最新规则已公布 · 2027 年份待更新",
      tags: ["建筑设计", "跨学科", "可持续", "城市", "材料研究"],
      intro: "延续 polytechnic 建筑师培养，以建筑、城市和领土尺度的项目为核心，吸收理论与历史、社会学与经济、建造、结构、建筑物理、视觉艺术及多种表达方法。",
      suitable: "学业和建筑基本功强，已有规定长度的实践，并愿意在英语之外建立法语工作能力的申请者。",
      portfolio: "版面不大于 A4，优先学术设计项目；呈现图纸精度、多样表达、建筑到城市和领土的尺度变化，以及从概念到材料性的完整链条。",
      requirements: "优秀建筑本科；须有 12 个月实践，其中至少连续 6 个月在同一建筑单位。学校建议法语或英语一门优秀、另一门良好，并建议教学语言至少 C1。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
      warning: "这是法英双语环境，不能保证所有 studio 与课程均可零法语完成；实践年限是申请前必须优先核查的硬条件。",
      url: "https://www.epfl.ch/education/master/programs/architecture/"
    }]
  },
  {
    id: "polimi",
    name: "Politecnico di Milano",
    cn: "米兰理工大学",
    city: "米兰 / 曼托瓦 / 皮亚琴察",
    country: "意大利",
    position: "以三条独立硕士路径分别培养综合专业建筑、历史城市与遗产介入、可持续建筑—景观设计能力。",
    programs: [
      {
        id: "polimi-architecture",
        name: "Architecture",
        degree: "MSc · Milano Leonardo",
        duration: "2 年",
        language: "英语路径 · 意大利语路径",
        tuition: "最高 €3,943.04 / 年（2026/27）",
        deadline: "2027 待公布 · 建议 2026.10 起准备",
      status: "最新公开：2026/27 · 2027 待更新",
        tags: ["建筑设计", "技术整合", "专业实践", "再利用"],
        intro: "以 polytechnic culture 综合人文艺术与科学技术，并以多学科设计 workshop 为核心，处理既有空间更新、脆弱自然与人造环境、可持续性、技术创新及建筑师的社会责任。",
        suitable: "建筑本科和课程匹配度高，希望继续全面专业建筑训练，并能同时呈现空间、技术和既有环境判断的申请者。",
        portfolio: "展示完整建筑设计链条：概念、总图、平立剖、空间、结构、材料与技术整合；不要只用旧项目名定位申请方向。",
        requirements: "建筑本科、课程匹配与作品集；中国学历当前最低 GPA 80%。所有 MSc 申请者须提交认可的英语证明，当前 IELTS 6.0 等；一次最多申请两个 MSc。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "须在英语与意大利语教学路径中明确选择；英文项目国际生仍有毕业前完成 Italian OFA 的义务。建筑与设计仅 9 月入学。",
        url: "https://www.polimi.it/en/education/laurea-magistrale-programmes/programme-detail/architecture"
      },
      {
        id: "polimi-adh",
        name: "Architectural Design and History",
        degree: "MSc · Mantova",
        duration: "2 年",
        language: "英语",
        tuition: "最高 €3,943.04 / 年（2026/27）",
        deadline: "2027 待公布 · 建议 2026.10 起准备",
      status: "最新公开：2026/27 · 2027 待更新",
        tags: ["建筑设计", "建筑历史", "历史城市", "遗产", "修复"],
        intro: "以建筑设计与历史的关系为主线，结合测绘与修复、历史语境中的建筑—景观设计；第二年扩展至历史城市设计、建成环境可持续性和建筑遗产管理。",
        suitable: "对历史城市、遗产、更新与当代介入有持续项目积累，能够把历史判断转译为空间和材料策略的建筑本科生。",
        portfolio: "强化测绘和场地证据、历史条件、保护与更新策略、建筑空间和材料构造之间的连续性。",
        requirements: "建筑本科等值性、既往学业与作品集比较评审；中国学历当前最低 GPA 80%，所有 MSc 申请者须满足英语要求。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "全英文不等于只看概念表达；历史研究必须落实到可读的建筑图纸、修复判断与当代设计结果。国际生仍有 Italian OFA。",
        url: "https://www.polimi.it/en/education/laurea-magistrale-programmes/programme-detail/architectural-design-and-history"
      },
      {
        id: "polimi-sald",
        name: "Sustainable Architecture and Landscape Design",
        degree: "MSc · Piacenza",
        duration: "2 年",
        language: "英语",
        tuition: "最高 €3,943.04 / 年（2026/27）",
        deadline: "2027 待公布 · 建议 2026.10 起准备",
      status: "最新公开：2026/27 · 2027 待更新",
        tags: ["可持续", "气候", "公共性", "城市", "设计研究"],
        intro: "以设计研究连接建筑与景观，回应气候变化、资源耗竭和环境退化，并从具体场地研究文化、政治、媒介、环境与正义议题及影响土地和生命的行星过程。",
        suitable: "具有建筑—景观、多尺度生态、气候适应或公共空间项目，并能用证据支撑设计判断的建筑本科生。",
        portfolio: "用场地、生态和气候证据建立从领土、景观到建筑与材料的尺度链条，避免把可持续简化为性能标签。",
        requirements: "建筑本科、课程匹配与作品集；中国学历当前最低 GPA 80%，所有 MSc 申请者须满足英语要求。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "这是建筑与景观设计研究路径，不等于普通 Landscape Architecture，也不应只做环境性能展示。国际生仍有 Italian OFA。",
        url: "https://www.polimi.it/en/education/laurea-magistrale-programmes/programme-detail/sustainable-architecture-and-landscape-design"
      }
    ]
  },
  {
    id: "aa",
    name: "Architectural Association School of Architecture",
    cn: "英国建筑联盟学院（AA）",
    city: "伦敦",
    country: "英国 · 英格兰",
    position: "以独立设计研究、实验性 studio 与跨尺度建筑实践形成多条高度专门化的研究生路径。",
    programs: [
      {
        id: "aa-drl",
        name: "Architecture and Urbanism (DRL)",
        degree: "MArch",
        duration: "16 个月",
        language: "英语 · 按当轮要求",
        tuition: "最新学费资料：2026/27（按项目）· 2027 待公布",
        deadline: "最新：2026 轮 Early 01.23 / Late 03.06 · 2027 待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["建筑设计", "计算设计", "设计研究", "跨学科"],
        intro: "Design Research Laboratory 以团队式、后专业设计研究处理建筑与城市问题，方法跨越计算、系统思维、人工智能、机器人和新型集体设计实践。",
        suitable: "已有建筑或相关专业训练，希望把计算工具、系统研究与实验性建筑命题结合的申请者。",
        portfolio: "突出研究问题、迭代过程、团队中的个人贡献，以及技术方法如何产生可读的空间与建筑结果。",
        requirements: "相关本科或专业背景、数字作品集、个人陈述、推荐材料与英语证明；最终按 2027 admissions page 核查。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "这是 16 个月的 post-professional MArch，不应自动等同于英国职业注册 Part 2 路径。",
        url: "https://www.aaschool.ac.uk/school/programmes/taught-postgraduate-programmes/architecture-and-urbanism-drl"
      },
      {
        id: "aa-emtech",
        name: "Emergent Technologies and Design",
        degree: "MArch / MSc",
        duration: "16 个月",
        language: "英语 · 按当轮要求",
        tuition: "最新学费资料：2026/27（按项目）· 2027 待公布",
        deadline: "最新：2026 轮 Early 01.23 / Late 03.06 · 2027 待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["计算设计", "材料研究", "数字制造", "设计研究"],
        intro: "面向建筑与工程背景，以生物学启发的系统、计算设计、结构与材料实验、制造和环境性能研究新兴建筑技术。",
        suitable: "具备建筑、工程、计算或材料基础，希望进行技术—设计交叉研究的申请者。",
        portfolio: "说明算法、实验、模拟或制造如何改变结构、材料、环境表现和空间，而不是只展示形式生成。",
        requirements: "建筑、工程或相关本科；数字作品集、申请陈述、推荐材料及英语证明按当轮要求。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "MArch 与 MSc 的既往学历资格和毕业成果不同，申请前必须确认适用学位路线。",
        url: "https://www.aaschool.ac.uk/school/programmes/taught-postgraduate-programmes/emergent-technologies-and-design"
      },
      {
        id: "aa-housing-urbanism",
        name: "Housing and Urbanism",
        degree: "MA / MArch",
        duration: "MA 12 个月 · MArch 16 个月",
        language: "英语 · 按当轮要求",
        tuition: "最新学费资料：2026/27（按项目）· 2027 待公布",
        deadline: "最新：2026 轮 Early 01.23 / Late 03.06 · 2027 待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["城市研究", "住房", "公共政策", "建筑设计"],
        intro: "把建筑设计与当代城市战略连接，研究住房、生活方式、密度、城市集聚、非正规性及空间策略与社会政策之间的关系。",
        suitable: "有住房、城市更新、公共空间、社会研究或城市政策项目，并希望保持空间设计介入的申请者。",
        portfolio: "用城市证据、空间类型、政策条件与建筑或城市设计方案形成连续论证。",
        requirements: "相关本科或专业经验；MA 与 MArch 分别按当轮学历、作品集和研究材料要求申请。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "MA 和 MArch 的学制及成果要求不同；项目关注城市主义，不是通用职业建筑硕士。",
        url: "https://www.aaschool.ac.uk/school/programmes/taught-postgraduate-programmes/housing-and-urbanism"
      },
      {
        id: "aa-sed",
        name: "Sustainable Environmental Design",
        degree: "MSc / MArch",
        duration: "MSc 12 个月 · MArch 16 个月",
        language: "英语 · 按当轮要求",
        tuition: "最新学费资料：2026/27（按项目）· 2027 待公布",
        deadline: "最新：2026 轮 Early 01.23 / Late 03.06 · 2027 待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["可持续", "环境性能", "气候", "设计研究"],
        intro: "将环境分析、建筑性能模拟与设计研究结合，在不同气候和建成环境中发展低能耗、适应性与以使用者为中心的建筑策略。",
        suitable: "已有气候、被动式设计、环境模拟、既有建筑更新或性能—空间整合经验的申请者。",
        portfolio: "让气候数据、使用行为和性能验证对应到剖面、围护、材料、系统与空间选择。",
        requirements: "建筑、工程或相关背景；MSc/MArch 资格、作品集、陈述和英语证明以 2027 当轮为准。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "不要把环境分析图当作建筑结果；MSc 与 MArch 路线也不自动具有相同职业资格。",
        url: "https://www.aaschool.ac.uk/school/programmes/taught-postgraduate-programmes/sustainable-environmental-design"
      }
    ]
  },
  {
    id: "cardiff",
    name: "Cardiff University",
    cn: "卡迪夫大学",
    city: "卡迪夫",
    country: "英国 · 威尔士",
    position: "以 grounded creativity 连接专业实践、建筑技术、气候责任和独立设计立场的职业建筑教育。",
    programs: [{
      id: "cardiff-march",
      name: "Master of Architecture",
      degree: "MArch · ARB/RIBA Part 2",
      duration: "2 年 · 第一年以实践为主",
      language: "英语 · 按当轮要求",
      tuition: "2026/27 海外：第 1 年 £15,350 · 第 2 年 £30,700",
      deadline: "最新：2026 轮通常 08 月底前 · 2027 待公布",
      status: "最新公开：2026/27 · 2027 待更新",
      tags: ["建筑设计", "专业实践", "技术整合", "可持续"],
      intro: "第一年主要在建筑事务所实践并配合短期课程，第二年完成论文与设计 thesis；以现实议题、气候责任、技术表现和个人专业立场构成综合 Part 2 训练。",
      suitable: "已取得 Part 1 或可确认等值、能落实入学前工作安置，并希望走英国职业建筑路径的申请者。",
      portfolio: "呈现完整建筑设计、技术整合和批判反思，同时用实践项目说明个人职责与专业成长。",
      requirements: "建筑 Part 1 或等值；入学前须自行落实符合要求的 architectural practice placement，另按当轮提交作品集、学历及英语材料。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
      warning: "第一年实践岗位需在注册前取得；中国建筑本科不能只凭学位名称假定 Part 1 等值。",
      url: "https://www.cardiff.ac.uk/study/postgraduate/taught/courses/course/master-of-architecture-march"
    }]
  },
  {
    id: "gsa",
    name: "Glasgow School of Art",
    cn: "格拉斯哥艺术学院",
    city: "格拉斯哥",
    country: "英国 · 苏格兰",
    position: "在艺术学院语境中以专题化 Architectural Studies 连接建筑设计、城市、环境和数字实践。",
    programs: [
      {
        id: "gsa-urban-buildings",
        name: "Architectural Studies: Urban Buildings",
        degree: "MArch Architectural Studies",
        duration: "通常 1 年 · 以 2027 为准",
        language: "英语 · 按当轮要求",
        tuition: "£26,420 / 年（最新：2026/27 国际生）",
        deadline: "最新：需签证者 2026.06.30 · 2027 待公布",
        status: "最新公开：2026/27 · 项目验证状态待确认",
        tags: ["建筑设计", "城市", "设计研究"],
        intro: "以城市建筑为研究对象，在建筑与城市尺度之间发展设计命题，并通过 studio 和独立项目形成专题化建筑研究。",
        suitable: "希望从建筑类型、城市形态与公共生活关系深化设计研究的建筑申请者。",
        portfolio: "突出建筑与城市尺度转换、类型与公共空间判断，以及清晰的个人研究问题。",
        requirements: "相关本科、数字作品集、陈述、推荐及英语证明，按学校 2027 applicant guidelines 核查。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "官网当前将该路径标为 subject to validation；学位名称、开放状态和费用必须在 2027 申请前再次确认。",
        url: "https://www.gsa.ac.uk/postgraduate-degrees/master-of-architectural-studies-urban-buildings"
      },
      {
        id: "gsa-energy-environment",
        name: "Architectural Studies: Energy and Environment",
        degree: "MArch Architectural Studies",
        duration: "通常 1 年 · 以 2027 为准",
        language: "英语 · 按当轮要求",
        tuition: "£26,420 / 年（最新：2026/27 国际生）",
        deadline: "最新：需签证者 2026.06.30 · 2027 待公布",
        status: "最新公开：2026/27 · 项目验证状态待确认",
        tags: ["可持续", "环境性能", "气候", "建筑设计"],
        intro: "围绕能源、环境与建筑设计的关系发展专题研究，把气候与性能判断转化为空间、围护、材料和使用策略。",
        suitable: "已有环境设计、低碳、改造、性能模拟或气候适应项目的建筑申请者。",
        portfolio: "用可核验的环境证据说明设计变化，并保留完整建筑图纸与材料、构造判断。",
        requirements: "相关本科与数字作品集；具体语言、文件格式和面试按 2027 指南。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "官网当前将该路径标为 subject to validation；不可把暂定课程信息写成已确认 2027 offer 条件。",
        url: "https://www.gsa.ac.uk/postgraduate-degrees/master-of-architectural-studies-energy-and-environment"
      },
      {
        id: "gsa-digital-creativity",
        name: "Architectural Studies: Digital Creativity",
        degree: "MArch Architectural Studies",
        duration: "通常 1 年 · 以 2027 为准",
        language: "英语 · 按当轮要求",
        tuition: "£26,420 / 年（最新：2026/27 国际生）",
        deadline: "最新：需签证者 2026.06.30 · 2027 待公布",
        status: "最新公开：2026/27 · 项目验证状态待确认",
        tags: ["计算设计", "数字制造", "实验建筑", "设计研究"],
        intro: "以数字创造力为专题，将计算媒介、制造、视觉化和实验性空间方法纳入建筑设计研究。",
        suitable: "具备数字设计、交互、制造或新媒介实践，同时能够落实建筑尺度结果的申请者。",
        portfolio: "展示数字方法、实验过程与空间或建造结果之间的因果关系，避免纯软件效果展示。",
        requirements: "相关本科、数字作品集和项目申请材料；2027 开放与验证状态须以官网为准。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "官网当前将该路径标为 subject to validation；正式学位结构和课程内容仍可能调整。",
        url: "https://www.gsa.ac.uk/postgraduate-degrees/master-of-architectural-studies-digital-creativity"
      }
    ]
  },
  {
    id: "manchester",
    name: "Manchester School of Architecture",
    cn: "曼彻斯特建筑学院",
    city: "曼彻斯特",
    country: "英国 · 英格兰",
    position: "由曼彻斯特大学与曼彻斯特城市大学联合教学，在职业建筑、城市研究和既有建筑再利用之间形成清晰分流。",
    programs: [
      {
        id: "manchester-march",
        name: "Architecture",
        degree: "MArch · ARB/RIBA Part 2",
        duration: "2 年",
        language: "英语 · 按当轮要求",
        tuition: "£32,000 / 年（最新：2026 入学国际生）",
        deadline: "最新申请页：2026/27 开放 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["建筑设计", "专业实践", "社会参与", "再利用"],
        intro: "以 atelier 与设计项目深化专业建筑能力，持续处理气候紧急状态、既有建筑适应性再利用及城市社会议题，并连接实践、客户和专业网络。",
        suitable: "具备 Part 1 或可确认等值、建筑设计基本功完整，并希望走英国 Part 2 路径的申请者。",
        portfolio: "提供从命题到综合设计、技术、环境与表达的完整项目，并说明实践经验与个人贡献。",
        requirements: "Part 1 或学校认可的等值建筑资格、作品集、陈述、学历与英语材料；海外资格先做等值核查。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "联合授予不改变 Part 1/Part 2 资格门槛；中国本科申请者应在投入作品集前确认资格可接受性。",
        url: "https://www.manchester.ac.uk/study/masters/courses/list/09342/march-architecture/"
      },
      {
        id: "manchester-adaptive-reuse",
        name: "Architecture and Adaptive Reuse",
        degree: "MA",
        duration: "1 年",
        language: "英语 · 按当轮要求",
        tuition: "£28,500 / 年（最新：2026 入学国际生）",
        deadline: "最新申请页：2026/27 开放 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["再利用", "遗产", "可持续", "材料研究"],
        intro: "从环境、社会、居住和经济影响研究建筑再利用，并将遗产、记忆、社区、保护、建造、环境控制和材料转化为设计提案。",
        suitable: "有既有建筑改造、遗产、材料、社区或低碳更新项目，希望进入专题硕士的申请者。",
        portfolio: "把现状调查、价值判断、保留与拆改策略、环境和构造细节连接为完整更新方案。",
        requirements: "相关建筑或设计背景、作品集、个人陈述、学历与英语材料，具体标准按 2027 页面。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "这是 1 年制专题 MA，不是 MArch Part 2 的替代品。",
        url: "https://www.manchester.ac.uk/study/masters/courses/list/20076/ma-architecture-and-adaptive-reuse/"
      },
      {
        id: "manchester-urbanism",
        name: "Architecture and Urbanism",
        degree: "MA",
        duration: "1 年",
        language: "英语 · 按当轮要求",
        tuition: "£28,500 / 年（最新：2026 入学国际生）",
        deadline: "最新申请页：2026/27 开放 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["城市设计", "城市研究", "社会空间", "设计研究"],
        intro: "以城市作为物质与文化建构进行批判调查，通过研究、数据解释与设计综合项目形成建筑和城市主义立场。",
        suitable: "已有城市、住房、公共空间、规划或跨尺度建筑项目，希望发展研究—设计结合能力的申请者。",
        portfolio: "呈现田野、地图、城市证据与建筑或城市设计命题的连续性。",
        requirements: "相关本科、作品集与申请材料；入学条件和英语要求以 2027 官网为准。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "这是 1 年制 Architecture and Urbanism MA，不授予 Part 2。",
        url: "https://www.manchester.ac.uk/study/masters/courses/list/07785/ma-architecture-and-urbanism/"
      }
    ]
  },
  {
    id: "newcastle",
    name: "Newcastle University",
    cn: "纽卡斯尔大学",
    city: "纽卡斯尔",
    country: "英国 · 英格兰",
    position: "以 research through design、vertical studio、社区合作与 live build 连接专业建筑和高级设计研究。",
    programs: [
      {
        id: "newcastle-march",
        name: "Architecture",
        degree: "MArch · ARB/RIBA Part 2",
        duration: "2 年",
        language: "英语 · 按当轮要求",
        tuition: "最新官网页：2026 入学，海外金额未显示 · 2027 待公布",
        deadline: "最新申请页：2026 入学 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["建筑设计", "专业实践", "设计建造", "城市设计"],
        intro: "通过 vertical studio、research by design 与建筑 thesis 深化批判和综合设计能力，并可接触城市设计、规划、交流及社区 live build。",
        suitable: "具备 Part 1 或等值、希望结合个人研究、综合建筑设计和社区实践的申请者。",
        portfolio: "突出复杂建筑项目的完整性、研究主题、技术与生态判断，以及实际制作或社区合作经验。",
        requirements: "Part 1 或经确认的等值建筑资格、作品集、学历和英语材料；国际资格须提前核查。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "可选城市设计/规划模块不等于另授城市设计学位；Part 2 门槛仍适用。",
        url: "https://www.ncl.ac.uk/postgraduate/degrees/5843f/"
      },
      {
        id: "newcastle-aad",
        name: "Advanced Architectural Design",
        degree: "MSc",
        duration: "1 年",
        language: "英语 · 按当轮要求",
        tuition: "£26,500 / 年（最新：2026 入学国际生）",
        deadline: "最新申请页：2026 入学 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["建筑设计", "设计研究", "技术整合", "可持续"],
        intro: "以一年制设计 thesis 和专题 studio 推进 research-led architectural enquiry，综合语境分析、材料与技术、生态伦理及个人设计兴趣。",
        suitable: "已完成建筑或相关设计本科，希望深化独立设计研究但不以 Part 2 为直接目标的申请者。",
        portfolio: "用一至两个完整项目证明研究命题、反复推演、建筑表达和技术—环境整合能力。",
        requirements: "相关本科、设计作品集、个人陈述、学历和英语材料，以 2027 course page 为准。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "MSc Advanced Architectural Design 不是 Part 2 职业资格课程。",
        url: "https://www.ncl.ac.uk/postgraduate/degrees/5383f/"
      }
    ]
  },
  {
    id: "rca",
    name: "Royal College of Art",
    cn: "皇家艺术学院",
    city: "伦敦",
    country: "英国 · 英格兰",
    position: "在艺术与设计学院环境中，以批判性、实践导向和跨学科方法重新定义建筑、城市与环境设计。",
    programs: [
      {
        id: "rca-architecture",
        name: "Architecture",
        degree: "MA · ARB/RIBA Part 2",
        duration: "2 年 · 240 credits",
        language: "英语 · IELTS 6.5（单项 ≥5.5）",
        tuition: "2026/27 海外 £29,000 / 年",
        deadline: "2027 轮待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["建筑设计", "批判实践", "社会生态", "设计研究"],
        intro: "把建筑视为回应政治、社会、生态与伦理问题的实践媒介，通过 design-led research、实验方法和独立方向发展 Part 2 能力。",
        suitable: "已具 Part 1 或等值、个人立场鲜明，能把批判议题转化为成熟建筑设计的申请者。",
        portfolio: "精选少量项目说明问题、方法、反思与空间结果；视频陈述需围绕作品过程和个人贡献。",
        requirements: "Part 1 或可接受等值背景、作品集与两分钟视频等当轮材料；英语当前为 IELTS 6.5、单项 5.5。",
        interview: "少数情况可能：2027 硕士流程仅在无法凭材料决定时安排线上或现场面试。",
        warning: "RCA 的学位名为 MA Architecture，但属于两年制 Part 2；不要因 MA 名称把它与一年制专题硕士混淆。",
        url: "https://www.rca.ac.uk/study/programme-finder/architecture-ma/"
      },
      {
        id: "rca-city-design",
        name: "City Design",
        degree: "MA",
        duration: "1 年 · 45 周 · 180 credits",
        language: "英语 · IELTS 6.5（单项 ≥5.5）",
        tuition: "2026/27 海外 £39,200 / 全项目",
        deadline: "2027 轮待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["城市设计", "公共政策", "社会空间", "跨学科"],
        intro: "从街道、街区到社区尺度研究城市共同生活，将 studio、空间正义、政策规划、数字工具及社会科学连接为转型性城市设计实践。",
        suitable: "来自建筑、景观、规划或相关领域，并关注住房、治理、气候和空间正义的申请者。",
        portfolio: "用城市证据、利益相关者、政策条件与空间提案建立清晰论证，说明设计的公共后果。",
        requirements: "相关本科或专业经验、作品集、陈述/视频等当轮材料；当前英语为 IELTS 6.5、单项 5.5。",
        interview: "少数情况可能：2027 硕士流程仅在无法凭材料决定时安排线上或现场面试。",
        warning: "这是 1 年制 City Design MA，不等于职业建筑 Part 2。",
        url: "https://www.rca.ac.uk/study/programme-finder/city-design-ma/"
      },
      {
        id: "rca-environmental",
        name: "Environmental Architecture",
        degree: "MA",
        duration: "1 年 · 45 周 · 180 credits",
        language: "英语 · IELTS 6.5（单项 ≥5.5）",
        tuition: "2026/27 海外 £39,200 / 全项目",
        deadline: "2027 轮待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["社会生态", "气候", "跨学科", "设计研究"],
        intro: "融合设计、艺术与科学，围绕气候前线地区、生态系统、资源开采、能源转型、环境法、气候正义及多物种关系发展环境建筑实践。",
        suitable: "关注领土、景观、环境冲突、社区与气候正义，并能接受跨学科田野研究的申请者。",
        portfolio: "展示场地与利益相关者研究、环境证据、媒介实验和空间介入之间的关系，不把项目缩成绿色技术展示。",
        requirements: "相关本科或经验、作品集及当轮陈述材料；当前英语为 IELTS 6.5、单项 5.5。",
        interview: "少数情况可能：2027 硕士流程仅在无法凭材料决定时安排线上或现场面试。",
        warning: "项目更接近环境设计研究和实践，不是传统建筑师综合训练或 Part 2。",
        url: "https://www.rca.ac.uk/study/programme-finder/environmental-architecture-ma/"
      }
    ]
  },
  {
    id: "ucl",
    name: "University College London",
    cn: "伦敦大学学院（UCL Bartlett）",
    city: "伦敦",
    country: "英国 · 英格兰",
    position: "以 unit / research cluster 体系覆盖职业建筑、先进计算设计、城市形态和生物—材料技术研究。",
    programs: [
      {
        id: "ucl-architecture",
        name: "Architecture",
        degree: "MArch · ARB/RIBA Part 2",
        duration: "2 年",
        language: "英语 · UCL Level 1",
        tuition: "2026/27 海外 £35,400 / 第 1 年",
        deadline: "最新：2025.10.20—2026.02.27 · 2027 待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["建筑设计", "专业实践", "技术整合", "设计研究"],
        intro: "以 design unit 推进高级建筑设计、技术与理论能力，在多样议题和方法中完成综合设计与独立立场，支持英国 Part 2 进程。",
        suitable: "已取得 Part 1 或学校认可等值、建筑基本功强，能适应高强度 unit 文化的申请者。",
        portfolio: "用完整项目证明概念、场地、空间、技术、材料和表达能力，并明确设计过程及个人贡献。",
        requirements: "建筑学高 2:1 或等值、通常至少 1 年本科毕业后的专业实践、设计作品集及当轮申请材料；海外学历资格须先核查。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "2026/27 海外学费所列为第一年，第二年可能调整；非英国 Part 1 学历不能自动视为等值。",
        url: "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/architecture"
      },
      {
        id: "ucl-architectural-design",
        name: "Architectural Design",
        degree: "MArch",
        duration: "1 年 · 180 credits",
        language: "英语 · UCL Level 1",
        tuition: "2026/27 海外 £42,700 / 全项目",
        deadline: "最新：需签证 2025.10.20—2026.06.26 · 2027 待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["计算设计", "人工智能", "数字制造", "实验建筑"],
        intro: "研究先进建筑与科学技术的交汇，research clusters 覆盖计算、AI、机器人、生成设计、沉浸式媒介、数字制造和新材料系统。",
        suitable: "有实验设计、计算、机器人、AI、制造或新媒介基础，希望进入 B-Pro 研究环境的申请者。",
        portfolio: "说明技术实验的建筑问题、过程和结果；代码、算法或机器输出必须对应空间、材料或建造判断。",
        requirements: "合适专业本科或相关经验、设计/创意作品集及申请材料；当前英语为 UCL Level 1。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "这是 1 年制 post-professional MArch，不是 Bartlett Architecture MArch Part 2。",
        url: "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/architectural-design"
      },
      {
        id: "ucl-urban-design",
        name: "Urban Design",
        degree: "MArch",
        duration: "1 年 · 180 credits",
        language: "英语 · UCL Level 1",
        tuition: "2026/27 海外 £42,700 / 全项目",
        deadline: "最新：需签证 2025.10.20—2026.06.26 · 2027 待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["城市设计", "城市研究", "设计研究", "公共性"],
        intro: "以项目和研究驱动的 studio 探索城市空间结构、城市形态及其改善方式，把理论研究转化为创新的城市设计提案。",
        suitable: "具有建筑、城市、景观或规划设计基础，并能在大尺度证据与空间精度之间转换的申请者。",
        portfolio: "呈现城市分析、形态规则、公共空间、类型与设计方案之间的连续推演。",
        requirements: "相关本科或专业经验、设计作品集和当轮申请材料；英语标准按 UCL Level 1。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "Urban Design MArch 为一年制专题项目，不属于 Architecture MArch Part 2。",
        url: "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/urban-design"
      },
      {
        id: "ucl-bio-integrated",
        name: "Bio-Integrated Design",
        degree: "MArch",
        duration: "2 年 · 300 credits",
        language: "英语 · UCL Level 1",
        tuition: "2026/27 海外 £39,200 / 第 1 年",
        deadline: "最新：需签证 2025.10.20—2026.07.10 · 2027 待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["材料研究", "生物设计", "数字制造", "跨学科"],
        intro: "在建筑、生命科学与工程之间研究生物材料、生长系统、计算和制造，通过实验室与设计 studio 形成跨学科 bio-integrated design。",
        suitable: "具备建筑、设计、工程或科学基础，愿意进行长期材料、生物与计算实验的申请者。",
        portfolio: "强调实验设计、记录、失败与迭代，并把微观材料或生物过程转化到建筑和环境尺度。",
        requirements: "合适学科本科、作品集及当轮申请文件；申请者需证明可承担跨学科技术课程。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "这是两年制跨学科 MArch，不等同于 Part 2；第二年费用和具体 research stream 须按当轮确认。",
        url: "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/bio-integrated-design"
      }
    ]
  },
  {
    id: "bath",
    name: "University of Bath",
    cn: "巴斯大学",
    city: "巴斯",
    country: "英国 · 英格兰",
    position: "将学期实践、建筑科学、可持续城市设计与综合设计 studio 紧密结合的 Part 2 路径。",
    programs: [{
      id: "bath-march",
      name: "Architecture",
      degree: "MArch (Hons) · ARB/RIBA Part 2",
      duration: "2 年 · 含一学期实践",
      language: "英语 · IELTS 7.0（单项 ≥6.5）",
      tuition: "2026/27 海外：第 1 年 £20,445 · 第 2 年当年全费参考 £32,000",
      deadline: "2026 轮为 04.30 · 2027 待公布",
      status: "最新公开：2026/27 · 2027 待更新",
      tags: ["建筑设计", "专业实践", "技术整合", "城市设计"],
      intro: "第一年先进行一学期建筑实践，再学习历史、理论、建筑科学、可持续与城市设计；第二年以研究和综合 studio 发展个人建筑立场。",
      suitable: "已有高质量建筑本科、Part 1 等值与约 9 个月实践，并重视设计—技术整合的申请者。",
      portfolio: "约 30 面 A3，重点呈现最终项目的概念与分析、总体和三维空间、材料性与细部，并控制实习作品比例。",
      requirements: "高 2:1 或等值建筑本科、Part 1 或通过 ARB prescribed examination；通常要求毕业后 9 个月实践，当前 IELTS 7.0、单项 6.5。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
      warning: "Bath 将 MArch 按 undergraduate funding/course 体系管理；海外申请者的 Part 1 等值是注册前硬条件。",
      url: "https://www.bath.ac.uk/courses/undergraduate-2026/architecture/march-architecture/"
    }]
  },
  {
    id: "cambridge",
    name: "University of Cambridge",
    cn: "剑桥大学",
    city: "剑桥",
    country: "英国 · 英格兰",
    position: "以研究与设计的紧密结合提供职业 MArch 和建筑—城市研究型 MPhil，两者申请目标截然不同。",
    programs: [
      {
        id: "cambridge-march",
        name: "Master of Architecture",
        degree: "MArch · ARB/RIBA Part 2",
        duration: "2 年",
        language: "英语 · 当轮标准",
        tuition: "不适用：课程已停止招生",
        deadline: "不再接受申请（自 2025.10 起）",
        status: "已停止招生",
        tags: ["建筑设计", "设计研究", "专业实践", "技术整合"],
        intro: "两年制 Part 2 课程以 research and design 为结构核心，通过 studio、研究和综合建筑项目发展专业与学术能力。",
        suitable: "具备 Part 1 或可接受等值、学术成绩与建筑设计能力都很强，并有清晰研究兴趣的申请者。",
        portfolio: "以完整建筑设计、研究严谨性、技术整合和独立判断为主，避免只用学术写作或视觉风格代替综合项目。",
        requirements: "Part 1 或学校接受的等值资格、作品集与当轮申请材料；具体实践和英语条件以项目重开页面为准。",
        interview: "不适用：该旧 MArch 已停止招生，2025 年 10 月起不再接受新申请。",
        warning: "官网明确说明自 2025 年 10 月起不再接受该 MArch 申请；仅作为历史项目保留，不应进入 2027 选校清单。",
        url: "https://www.arct.cam.ac.uk/courses/postgraduate/master-architecture-march-degree-arbriba-part-2"
      },
      {
        id: "cambridge-maus",
        name: "Architecture and Urban Studies",
        degree: "MPhil",
        duration: "9 个月",
        language: "英语 · IELTS 7.5（单项通常 ≥7.0）",
        tuition: "最新费用资料：2026 入学 · 2027 学费及 college fee 待公布",
        deadline: "最新：2025.09.03—2026.03.05 · 2027 待公布",
        status: "最新公开：2026 · 2027 待更新",
        tags: ["城市研究", "建筑文化", "历史理论", "跨学科"],
        intro: "对当代建筑与城市问题进行高级研究，连接建筑、城市、社会、文化与环境议题，适合明确的研究方向而非以 studio 为主的职业训练。",
        suitable: "有强学术写作、研究方法和建筑/城市问题意识，计划进入研究、政策或博士路径的申请者。",
        portfolio: "若当轮要求提交视觉材料，应围绕研究问题选择；研究计划、写作和方法能力比作品数量更重要。",
        requirements: "高水平相关本科、研究陈述、推荐和英语证明；当前页面列较高英语要求，2027 以正式目录为准。",
        interview: "必需（入围后）：入围申请者参加线上面试。",
        warning: "这是 9 个月研究型 MPhil，不是 MArch、Part 2 或通用建筑设计 studio 项目。",
        url: "https://www.postgraduate.study.cam.ac.uk/courses/directory/aharmpaus"
      }
    ]
  },
  {
    id: "edinburgh",
    name: "University of Edinburgh",
    cn: "爱丁堡大学",
    city: "爱丁堡",
    country: "英国 · 苏格兰",
    position: "在 ESALA 体系中覆盖低碳职业建筑、建筑—景观研究、环境模拟和社会可持续城市策略。",
    programs: [
      {
        id: "edinburgh-march",
        name: "Architecture",
        degree: "MArch · ARB/RIBA Part 2",
        duration: "2 年",
        language: "英语 · 按当轮要求",
        tuition: "最新项目页：2026/27 · 2027 海外学费待公布",
        deadline: "最新：2026 轮已关闭 · 2027 通常 2026.10 开放",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["建筑设计", "专业实践", "低碳", "设计研究"],
        intro: "以主题 studio、创造性探究与学术严谨性发展低碳、场所化、包容和再生性的空间实践，并纳入建筑管理、实践与法律。",
        suitable: "具备 Part 1 或可接受等值，希望把独立建筑立场、社会环境责任与职业能力结合的申请者。",
        portfolio: "用完整项目说明场所、材料、碳、社会关系和技术如何共同形成建筑判断。",
        requirements: "Part 1 或学校认可的等值建筑资格、portfolio、学历、陈述和英语材料；国际资格先核查。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "MArch 属 Part 2 路径；不要与 ESALA 的一年制研究型 MSc 混为同一资格。",
        url: "https://study.ed.ac.uk/programmes/postgraduate-taught/420-architecture-master-of-arbriba-part-2"
      },
      {
        id: "edinburgh-asd",
        name: "Advanced Sustainable Design",
        degree: "MSc",
        duration: "1 年",
        language: "英语 · 按当轮要求",
        tuition: "最新项目页：2026/27 · 2027 海外学费待公布",
        deadline: "最新：2026 轮已关闭 · 2027 通常 2026.10 开放",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["可持续", "环境性能", "气候", "技术整合"],
        intro: "通过环境模拟、建筑性能与可持续设计方法研究低碳建成环境，把技术分析与建筑和城市设计决策结合。",
        suitable: "有环境设计、模拟、低碳建筑、再利用或建筑科学基础的申请者。",
        portfolio: "用性能证据、剖面、围护、系统、材料和使用模式说明环境策略的空间后果。",
        requirements: "建筑或相关建成环境本科，申请材料与英语要求按 2027 degree finder。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "这是 1 年制 MSc，不授予 Part 2；技术分析不能替代建筑设计能力。",
        url: "https://study.ed.ac.uk/programmes/postgraduate-taught/417-advanced-sustainable-design"
      },
      {
        id: "edinburgh-ale",
        name: "Architecture, Landscape and Environment",
        degree: "MSc",
        duration: "1 年",
        language: "英语 · 按当轮要求",
        tuition: "最新项目页：2026/27 · 2027 海外学费待公布",
        deadline: "最新：2026 轮已关闭 · 2027 通常 2026.10 开放",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["景观", "社会生态", "设计研究", "跨学科"],
        intro: "在建筑、景观与环境之间开展 design research，关注场地、生态、领土和空间实践的相互构成。",
        suitable: "有建筑—景观、生态场地、领土或环境艺术实践，希望跨学科深化的申请者。",
        portfolio: "展示从现场观察和环境证据到景观、建筑与材料介入的尺度链条。",
        requirements: "建筑、景观、艺术或相关设计背景；作品集和英语要求以 2027 页面为准。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "这是一年制跨学科 MSc，不等同于 Architecture MArch 或专业 Landscape Architecture MLA。",
        url: "https://study.ed.ac.uk/programmes/postgraduate-taught/1096-architecture-landscape-and-environment"
      },
      {
        id: "edinburgh-usd",
        name: "Urban Strategies and Design",
        degree: "MSc · 与 Heriot-Watt 联合教学",
        duration: "1 年",
        language: "英语 · 按当轮要求",
        tuition: "最新项目页：2026/27 · 2027 海外学费待公布",
        deadline: "最新：2026 轮已关闭 · 2027 通常 2026.10 开放",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["城市设计", "规划", "社会空间", "公共政策"],
        intro: "连接建筑驱动的城市设计与更高层级空间规划，研究塑造城市的社会、经济和政治过程，并形成不同尺度的城市策略与设计工具。",
        suitable: "来自建筑、景观、规划、地理或社会科学，关注城市转型和社会可持续性的申请者。",
        portfolio: "设计背景者用空间方案证明策略；非设计背景者则强化城市研究、数据、图示与介入方法。",
        requirements: "接受多学科背景；学历、陈述、可能的作品材料和英语条件以 2027 当轮为准。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "项目不提供职业建筑资格，也不是纯粹建筑 studio；申请叙事必须体现城市策略与跨学科能力。",
        url: "https://study.ed.ac.uk/programmes/postgraduate-taught/822-urban-strategies-and-design"
      }
    ]
  },
  {
    id: "sheffield",
    name: "University of Sheffield",
    cn: "谢菲尔德大学",
    city: "谢菲尔德",
    country: "英国 · 英格兰",
    position: "以 socially engaged design、research-led studio 与 Live Projects 连接职业建筑和独立设计研究。",
    programs: [
      {
        id: "sheffield-march",
        name: "Architecture",
        degree: "MArch · ARB/RIBA Part 2",
        duration: "2 年",
        language: "英语 · 按当轮要求",
        tuition: "£32,100 / 年（最新：2026/27 海外）",
        deadline: "最新：2026.08.28 · 2027 待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["建筑设计", "社会参与", "设计建造", "专业实践"],
        intro: "以研究型主题 studio、综合设计、论文和 Live Projects 培养社会参与的建筑实践，可从社区任务到城市总体和建筑细部展开。",
        suitable: "具备 Part 1 或可接受等值，关注社区、公共性和真实项目，同时能完成综合建筑设计的申请者。",
        portfolio: "除完整建筑方案外，突出与真实使用者、组织或场地合作的研究过程、反馈和设计后果。",
        requirements: "Part 1 或学校认可等值、作品集、500–600 字 statement、学历及英语材料。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "国际建筑本科需先确认 Part 1 等值与 funding/qualification 规则；Live Project 不降低综合设计门槛。",
        url: "https://sheffield.ac.uk/postgraduate/taught/courses/2026/architecture-march"
      },
      {
        id: "sheffield-ad",
        name: "Architectural Design",
        degree: "MA",
        duration: "1 年",
        language: "英语 · 按当轮要求",
        tuition: "£29,190 / 年（最新：2026/27 海外）",
        deadline: "最新申请页：2026 入学 · 2027 待公布",
        status: "最新公开：2026/27 · 2027 待更新",
        tags: ["建筑设计", "社会参与", "设计研究", "跨学科"],
        intro: "以 studio 探索建筑设计过程与方法，通过严谨的设计研究、Live Projects 和个人专题发展独特实践，也可作为 PhD by Design 的准备。",
        suitable: "希望深化设计方法、社会环境议题和 research through design，但不直接申请 Part 2 的申请者。",
        portfolio: "展示过程、方法、真实问题与建筑结果，避免只交成图；社会与环境主张应有空间证据。",
        requirements: "相关本科、设计作品集、陈述与英语证明，具体材料按 2027 项目页。",
        interview: "官网未列为常规环节：按申请材料/作品集评审；2027 简章发布后复核。",
        warning: "Architectural Design MA 是一年制研究型设计硕士，不等于 Architecture MArch Part 2。",
        url: "https://sheffield.ac.uk/postgraduate/taught/courses/2026/architectural-design-ma"
      }
    ]
  }
];
